/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoaclassificationstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACLASSIFICATIONSTRONGMNGD_API, not TCSOACLASSIFICATIONSTRONGMNGDEXPORT */

#define TCSOACLASSIFICATIONSTRONGMNGD_API TCSOACLASSIFICATIONSTRONGMNGDEXPORT

/* Support TCSOACLASSIFICATIONSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoaclassificationstrongmngd
#   if defined(__lint)
#       define TCSOACLASSIFICATIONSTRONGMNGDEXPORT       __export(tcsoaclassificationstrongmngd)
#       define TCSOACLASSIFICATIONSTRONGMNGDGLOBAL       extern __global(tcsoaclassificationstrongmngd)
#       define TCSOACLASSIFICATIONSTRONGMNGDPRIVATE      extern __private(tcsoaclassificationstrongmngd)
#   elif defined(_WIN32)
#       define TCSOACLASSIFICATIONSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOACLASSIFICATIONSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACLASSIFICATIONSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOACLASSIFICATIONSTRONGMNGDEXPORT
#       define TCSOACLASSIFICATIONSTRONGMNGDGLOBAL       extern
#       define TCSOACLASSIFICATIONSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACLASSIFICATIONSTRONGMNGDEXPORT       __export(tcsoaclassificationstrongmngd)
#       define TCSOACLASSIFICATIONSTRONGMNGDGLOBAL       extern __global(tcsoaclassificationstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACLASSIFICATIONSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOACLASSIFICATIONSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACLASSIFICATIONSTRONGMNGDEXPORT
#       define TCSOACLASSIFICATIONSTRONGMNGDGLOBAL       extern
#   endif
#endif

