/*==============================================================================
                Copyright (c) 2003-2005 UGS Corporation
                   Unpublished - All Rights Reserved
 ==============================================================================*/

/*
    File Description:

    The header file that defines the export symbols for the AIE library
 */

#define libaie                   -10001

#ifdef EXPORTLIBRARY
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libaie

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten iMAN code should use the XXX_API version, not XXXEXPORT */

#define AIE_API AIEEXPORT

/* Support AIEEXPORT for autogenerated code only */

#if IPLIB==libaie
#   if defined(__lint)
#       define AIEEXPORT       __export(aie)
#       define AIEGLOBAL       extern __global(aie)
#       define AIEPRIVATE      extern __private(aie)
#   elif defined(_WIN32)
#       define AIEEXPORT       __declspec(dllexport)
#       define AIEGLOBAL       extern __declspec(dllexport)
#       define AIEPRIVATE      extern
#   else
#       define AIEEXPORT
#       define AIEGLOBAL       extern
#       define AIEPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define AIEEXPORT       __export(aie)
#       define AIEGLOBAL       extern __global(aie)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define AIEEXPORT       __declspec(dllimport)
#       define AIEGLOBAL       extern __declspec(dllimport)
#   else
#       define AIEEXPORT
#       define AIEGLOBAL       extern
#   endif
#endif
