/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoatranslationstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOATRANSLATIONSTRONGMNGD_API, not TCSOATRANSLATIONSTRONGMNGDEXPORT */

#define TCSOATRANSLATIONSTRONGMNGD_API TCSOATRANSLATIONSTRONGMNGDEXPORT

/* Support TCSOATRANSLATIONSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoatranslationstrongmngd
#   if defined(__lint)
#       define TCSOATRANSLATIONSTRONGMNGDEXPORT       __export(tcsoatranslationstrongmngd)
#       define TCSOATRANSLATIONSTRONGMNGDGLOBAL       extern __global(tcsoatranslationstrongmngd)
#       define TCSOATRANSLATIONSTRONGMNGDPRIVATE      extern __private(tcsoatranslationstrongmngd)
#   elif defined(_WIN32)
#       define TCSOATRANSLATIONSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOATRANSLATIONSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOATRANSLATIONSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOATRANSLATIONSTRONGMNGDEXPORT
#       define TCSOATRANSLATIONSTRONGMNGDGLOBAL       extern
#       define TCSOATRANSLATIONSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOATRANSLATIONSTRONGMNGDEXPORT       __export(tcsoatranslationstrongmngd)
#       define TCSOATRANSLATIONSTRONGMNGDGLOBAL       extern __global(tcsoatranslationstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOATRANSLATIONSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOATRANSLATIONSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOATRANSLATIONSTRONGMNGDEXPORT
#       define TCSOATRANSLATIONSTRONGMNGDGLOBAL       extern
#   endif
#endif

