/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoadocumentmanagementstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOADOCUMENTMANAGEMENTSTRONGMNGD_API, not TCSOADOCUMENTMANAGEMENTSTRONGMNGDEXPORT */

#define TCSOADOCUMENTMANAGEMENTSTRONGMNGD_API TCSOADOCUMENTMANAGEMENTSTRONGMNGDEXPORT

/* Support TCSOADOCUMENTMANAGEMENTSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoadocumentmanagementstrongmngd
#   if defined(__lint)
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDEXPORT       __export(tcsoadocumentmanagementstrongmngd)
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDGLOBAL       extern __global(tcsoadocumentmanagementstrongmngd)
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDPRIVATE      extern __private(tcsoadocumentmanagementstrongmngd)
#   elif defined(_WIN32)
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDEXPORT
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDGLOBAL       extern
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDEXPORT       __export(tcsoadocumentmanagementstrongmngd)
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDGLOBAL       extern __global(tcsoadocumentmanagementstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDEXPORT
#       define TCSOADOCUMENTMANAGEMENTSTRONGMNGDGLOBAL       extern
#   endif
#endif

