/*==============================================================================
                Copyright (c) 2003-2005 UGS Corporation
                   Unpublished - All Rights Reserved
 ==============================================================================*/

/*
    File Description:

    The header file that defines the export symbols for the SUB_MGR library
 */

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libsub_mgr

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use SUB_MGR_API, not SUB_MGREXPORT */

#define SUB_MGR_API SUB_MGREXPORT

/* Support SUB_MGREXPORT for autogenerated schema/pif code only */

#if IPLIB==libsub_mgr
#   if defined(__lint)
#       define SUB_MGREXPORT       __export(sub_mgr)
#       define SUB_MGRGLOBAL       extern __global(sub_mgr)
#       define SUB_MGRPRIVATE      extern __private(sub_mgr)
#   elif defined(_WIN32)
#       define SUB_MGREXPORT       __declspec(dllexport)
#       define SUB_MGRGLOBAL       extern __declspec(dllexport)
#       define SUB_MGRPRIVATE      extern
#   else
#       define SUB_MGREXPORT
#       define SUB_MGRGLOBAL       extern
#       define SUB_MGRPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define SUB_MGREXPORT       __export(sub_mgr)
#       define SUB_MGRGLOBAL       extern __global(sub_mgr)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define SUB_MGREXPORT      __declspec(dllimport)
#       define SUB_MGRGLOBAL       extern __declspec(dllimport)
#   else
#       define SUB_MGREXPORT
#       define SUB_MGRGLOBAL       extern
#   endif
#endif

