/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoasystemsengineeringstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOASYSTEMSENGINEERINGSTRONGMNGD_API, not TCSOASYSTEMSENGINEERINGSTRONGMNGDEXPORT */

#define TCSOASYSTEMSENGINEERINGSTRONGMNGD_API TCSOASYSTEMSENGINEERINGSTRONGMNGDEXPORT

/* Support TCSOASYSTEMSENGINEERINGSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoasystemsengineeringstrongmngd
#   if defined(__lint)
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDEXPORT       __export(tcsoasystemsengineeringstrongmngd)
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDGLOBAL       extern __global(tcsoasystemsengineeringstrongmngd)
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDPRIVATE      extern __private(tcsoasystemsengineeringstrongmngd)
#   elif defined(_WIN32)
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDEXPORT
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDGLOBAL       extern
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDEXPORT       __export(tcsoasystemsengineeringstrongmngd)
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDGLOBAL       extern __global(tcsoasystemsengineeringstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDEXPORT
#       define TCSOASYSTEMSENGINEERINGSTRONGMNGDGLOBAL       extern
#   endif
#endif

