/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libcpd0soacpdcorestrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use CPD0SOACPDCORESTRONGMNGD_API, not CPD0SOACPDCORESTRONGMNGDEXPORT */

#define CPD0SOACPDCORESTRONGMNGD_API CPD0SOACPDCORESTRONGMNGDEXPORT

/* Support CPD0SOACPDCORESTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libcpd0soacpdcorestrongmngd
#   if defined(__lint)
#       define CPD0SOACPDCORESTRONGMNGDEXPORT       __export(cpd0soacpdcorestrongmngd)
#       define CPD0SOACPDCORESTRONGMNGDGLOBAL       extern __global(cpd0soacpdcorestrongmngd)
#       define CPD0SOACPDCORESTRONGMNGDPRIVATE      extern __private(cpd0soacpdcorestrongmngd)
#   elif defined(_WIN32)
#       define CPD0SOACPDCORESTRONGMNGDEXPORT       __declspec(dllexport)
#       define CPD0SOACPDCORESTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define CPD0SOACPDCORESTRONGMNGDPRIVATE      extern
#   else
#       define CPD0SOACPDCORESTRONGMNGDEXPORT
#       define CPD0SOACPDCORESTRONGMNGDGLOBAL       extern
#       define CPD0SOACPDCORESTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define CPD0SOACPDCORESTRONGMNGDEXPORT       __export(cpd0soacpdcorestrongmngd)
#       define CPD0SOACPDCORESTRONGMNGDGLOBAL       extern __global(cpd0soacpdcorestrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define CPD0SOACPDCORESTRONGMNGDEXPORT      __declspec(dllimport)
#       define CPD0SOACPDCORESTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define CPD0SOACPDCORESTRONGMNGDEXPORT
#       define CPD0SOACPDCORESTRONGMNGDGLOBAL       extern
#   endif
#endif

