// @<COPYRIGHT_START>@
// ===============================================
// Copyright 2008 UGS Corp. All Rights Reserved.
// ===============================================
// @<COPYRIGHT_END>@


#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY libextensionframework

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use EXTENSIONFRAMEWORK_API, not EXTENSIONFRAMEWORKEXPORT */

#define EXTENSIONFRAMEWORK_API EXTENSIONFRAMEWORKEXPORT

/* Support EXTENSIONFRAMEWORKEXPORT for autogenerated schema/pif code only */

#if IPLIB==libextensionframework
#   if defined(__lint)
#       define EXTENSIONFRAMEWORKEXPORT       __export(extensionframework)
#       define EXTENSIONFRAMEWORKGLOBAL       extern __global(extensionframework)
#       define EXTENSIONFRAMEWORKPRIVATE      extern __private(extensionframework)
#   elif defined(_WIN32)
#       define EXTENSIONFRAMEWORKEXPORT       __declspec(dllexport)
#       define EXTENSIONFRAMEWORKGLOBAL       extern __declspec(dllexport)
#       define EXTENSIONFRAMEWORKPRIVATE      extern
#   else
#       define EXTENSIONFRAMEWORKEXPORT
#       define EXTENSIONFRAMEWORKGLOBAL       extern
#       define EXTENSIONFRAMEWORKPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define EXTENSIONFRAMEWORKEXPORT       __export(extensionframework)
#       define EXTENSIONFRAMEWORKGLOBAL       extern __global(extensionframework)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define EXTENSIONFRAMEWORKEXPORT      __declspec(dllimport)
#       define EXTENSIONFRAMEWORKGLOBAL       extern __declspec(dllimport)
#   else
#       define EXTENSIONFRAMEWORKEXPORT
#       define EXTENSIONFRAMEWORKGLOBAL       extern
#   endif
#endif
