/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoachangemanagementstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACHANGEMANAGEMENTSTRONGMNGD_API, not TCSOACHANGEMANAGEMENTSTRONGMNGDEXPORT */

#define TCSOACHANGEMANAGEMENTSTRONGMNGD_API TCSOACHANGEMANAGEMENTSTRONGMNGDEXPORT

/* Support TCSOACHANGEMANAGEMENTSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoachangemanagementstrongmngd
#   if defined(__lint)
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDEXPORT       __export(tcsoachangemanagementstrongmngd)
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDGLOBAL       extern __global(tcsoachangemanagementstrongmngd)
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDPRIVATE      extern __private(tcsoachangemanagementstrongmngd)
#   elif defined(_WIN32)
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDEXPORT
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDGLOBAL       extern
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDEXPORT       __export(tcsoachangemanagementstrongmngd)
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDGLOBAL       extern __global(tcsoachangemanagementstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDEXPORT
#       define TCSOACHANGEMANAGEMENTSTRONGMNGDGLOBAL       extern
#   endif
#endif

