/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libads0soaadsfoundationstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use ADS0SOAADSFOUNDATIONSTRONGMNGD_API, not ADS0SOAADSFOUNDATIONSTRONGMNGDEXPORT */

#define ADS0SOAADSFOUNDATIONSTRONGMNGD_API ADS0SOAADSFOUNDATIONSTRONGMNGDEXPORT

/* Support ADS0SOAADSFOUNDATIONSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libads0soaadsfoundationstrongmngd
#   if defined(__lint)
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDEXPORT       __export(ads0soaadsfoundationstrongmngd)
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDGLOBAL       extern __global(ads0soaadsfoundationstrongmngd)
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDPRIVATE      extern __private(ads0soaadsfoundationstrongmngd)
#   elif defined(_WIN32)
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDEXPORT       __declspec(dllexport)
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDPRIVATE      extern
#   else
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDEXPORT
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDGLOBAL       extern
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDEXPORT       __export(ads0soaadsfoundationstrongmngd)
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDGLOBAL       extern __global(ads0soaadsfoundationstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDEXPORT      __declspec(dllimport)
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDEXPORT
#       define ADS0SOAADSFOUNDATIONSTRONGMNGDGLOBAL       extern
#   endif
#endif

