/*==============================================================================
                Copyright (c) 2003-2005 UGS Corporation
                   Unpublished - All Rights Reserved
 ==============================================================================*/

/*
    File Description:

    The header file that defines the export symbols for the TCTRUSHAPE library
 */

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtctrushape

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCTRUSHAPE_API, not TCTRUSHAPEEXPORT */

#define TCTRUSHAPE_API TCTRUSHAPEEXPORT

/* Support TCTRUSHAPEEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtctrushape
#   if defined(__lint)
#       define TCTRUSHAPEEXPORT       __export(tctrushape)
#       define TCTRUSHAPEGLOBAL       extern __global(tctrushape)
#       define TCTRUSHAPEPRIVATE      extern __private(tctrushape)
#   elif defined(_WIN32)
#       define TCTRUSHAPEEXPORT       __declspec(dllexport)
#       define TCTRUSHAPEGLOBAL       extern __declspec(dllexport)
#       define TCTRUSHAPEPRIVATE      extern
#   else
#       define TCTRUSHAPEEXPORT
#       define TCTRUSHAPEGLOBAL       extern
#       define TCTRUSHAPEPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCTRUSHAPEEXPORT       __export(tctrushape)
#       define TCTRUSHAPEGLOBAL       extern __global(tctrushape)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCTRUSHAPEEXPORT      __declspec(dllimport)
#       define TCTRUSHAPEGLOBAL       extern __declspec(dllimport)
#   else
#       define TCTRUSHAPEEXPORT
#       define TCTRUSHAPEGLOBAL       extern
#   endif
#endif

