/*==============================================================================
                Copyright (c) 2003-2005 UGS Corporation
                   Unpublished - All Rights Reserved
 ==============================================================================*/

/*
    File Description:

    The header file that defines the export symbols for the TCCOREEXT library
 */

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#error ExportLibrary is defined to be EXPORTLIBRARY
#endif

#define EXPORTLIBRARY            libtccoreext

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCCOREEXT_API, not TCCOREEXTEXPORT */

#define TCCOREEXT_API TCCOREEXTEXPORT

/* Support TCCOREEXTEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtccoreext
#   if defined(__lint)
#       define TCCOREEXTEXPORT       __export(tccoreext)
#       define TCCOREEXTGLOBAL       extern __global(tccoreext)
#       define TCCOREEXTPRIVATE      extern __private(tccoreext)
#   elif defined(_WIN32)
#       define TCCOREEXTEXPORT       __declspec(dllexport)
#       define TCCOREEXTGLOBAL       extern __declspec(dllexport)
#       define TCCOREEXTPRIVATE      extern
#   else
#       define TCCOREEXTEXPORT
#       define TCCOREEXTGLOBAL       extern
#       define TCCOREEXTPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCCOREEXTEXPORT       __export(tccoreext)
#       define TCCOREEXTGLOBAL       extern __global(tccoreext)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCCOREEXTEXPORT      __declspec(dllimport)
#       define TCCOREEXTGLOBAL       extern __declspec(dllimport)
#   else
#       define TCCOREEXTEXPORT
#       define TCCOREEXTGLOBAL       extern
#   endif
#endif
