// Copyright 2020 Siemens Digital Industries Software
// ==================================================
// Copyright 2011.
// Siemens Product Lifecycle Management Software Inc.
// All Rights Reserved.
// ==================================================
// Copyright 2020 Siemens Digital Industries Software

/**
    @file

    This file contains the declaration for the Dispatch Library Fnd0formulamgmt

*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libFnd0formulamgmt

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use FND0FORMULAMGMT_API, not FND0FORMULAMGMTEXPORT */

#define FND0FORMULAMGMT_API FND0FORMULAMGMTEXPORT

/* Support FND0FORMULAMGMTEXPORT for autogenerated schema/pif code only */

#if IPLIB==libFnd0formulamgmt || defined(LIBFND0FORMULAMGMT)
#   if defined(__lint)
#       define FND0FORMULAMGMTEXPORT        __export(Fnd0formulamgmt)
#       define FND0FORMULAMGMTGLOBAL        extern __global(Fnd0formulamgmt)
#       define FND0FORMULAMGMTPRIVATE       extern __private(Fnd0formulamgmt)
#   elif defined(_WIN32)
#       define FND0FORMULAMGMTEXPORT        __declspec(dllexport)
#       define FND0FORMULAMGMTGLOBAL        extern __declspec(dllexport)
#       define FND0FORMULAMGMTPRIVATE       extern
#   else
#       define FND0FORMULAMGMTEXPORT
#       define FND0FORMULAMGMTGLOBAL        extern
#       define FND0FORMULAMGMTPRIVATE       extern
#   endif
#else
#   if defined(__lint)
#       define FND0FORMULAMGMTEXPORT        __export(Fnd0formulamgmt)
#       define FND0FORMULAMGMTGLOBAL        extern __global(Fnd0formulamgmt)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define FND0FORMULAMGMTEXPORT        __declspec(dllimport)
#       define FND0FORMULAMGMTGLOBAL        extern __declspec(dllimport)
#   else
#       define FND0FORMULAMGMTEXPORT
#       define FND0FORMULAMGMTGLOBAL        extern
#   endif
#endif
