/*
   Copyright 2020 Siemens Digital Industries Software
   ==================================================
   Copyright 2015.
   Siemens Product Lifecycle Management Software Inc.
   All Rights Reserved.
   ==================================================
   Copyright 2020 Siemens Digital Industries Software
*/

/** 
    @file 

    This file undefines the export declarations for the library Cpc0cpdcm

    This file should be obsoleted once the autogenerated version is created in out/meta/Cpc0cpdcm folder.
    The autogenerated version will be generated after any metamodel operation is defined or overridden 
    in the cpdcm template.

*/

#include <common/library_indicators.h>

#if !defined(EXPORTLIBRARY)
#   error EXPORTLIBRARY is not defined
#endif

#undef EXPORTLIBRARY

#if !defined(LIBCPC0CPDCM) && !defined(IPLIB)
#   error IPLIB or LIBCPC0CPDCM is not defined
#endif

#undef CPC0CPDCM_API
#undef CPC0CPDCMEXPORT
#undef CPC0CPDCMGLOBAL
#undef CPC0CPDCMPRIVATE
