/*
   Copyright 2020 Siemens Digital Industries Software
   ==================================================
   Copyright 2015.
   Siemens Product Lifecycle Management Software Inc.
   All Rights Reserved.
   ==================================================
   Copyright 2020 Siemens Digital Industries Software
*/

/** 
    @file 

    This file contains the export declarations for the library Cpc0cpdcm

    This file should be obsoleted once the autogenerated version is created in out/meta/Cpc0cpdcm folder.
    The autogenerated version will be generated after any metamodel operation is defined or overridden 
    in the cpdcm template.

*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libCpc0cpdcm

#if !defined(LIBCPC0CPDCM) && !defined(IPLIB)
#   error IPLIB or LIBCPC0CPDCM is not defined
#endif

/* Handwritten code should use CPC0CPDCM_API, not CPC0CPDCMEXPORT */

#define CPC0CPDCM_API CPC0CPDCMEXPORT

#if IPLIB==libCpc0cpdcm || defined(LIBCPC0CPDCM)
#   if defined(__lint)
#       define CPC0CPDCMEXPORT       __export(Cpc0cpdcm)
#       define CPC0CPDCMGLOBAL       extern __global(Cpc0cpdcm)
#       define CPC0CPDCMPRIVATE      extern __private(Cpc0cpdcm)
#   elif defined(_WIN32)
#       define CPC0CPDCMEXPORT       __declspec(dllexport)
#       define CPC0CPDCMGLOBAL       extern __declspec(dllexport)
#       define CPC0CPDCMPRIVATE      extern
#   else
#       define CPC0CPDCMEXPORT
#       define CPC0CPDCMGLOBAL       extern
#       define CPC0CPDCMPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define CPC0CPDCMEXPORT       __export(Cpc0cpdcm)
#       define CPC0CPDCMGLOBAL       extern __global(Cpc0cpdcm)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define CPC0CPDCMEXPORT      __declspec(dllimport)
#       define CPC0CPDCMGLOBAL       extern __declspec(dllimport)
#   else
#       define CPC0CPDCMEXPORT
#       define CPC0CPDCMGLOBAL       extern
#   endif
#endif
