/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoacaestrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACAESTRONGMNGD_API, not TCSOACAESTRONGMNGDEXPORT */

#define TCSOACAESTRONGMNGD_API TCSOACAESTRONGMNGDEXPORT

/* Support TCSOACAESTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoacaestrongmngd
#   if defined(__lint)
#       define TCSOACAESTRONGMNGDEXPORT       __export(tcsoacaestrongmngd)
#       define TCSOACAESTRONGMNGDGLOBAL       extern __global(tcsoacaestrongmngd)
#       define TCSOACAESTRONGMNGDPRIVATE      extern __private(tcsoacaestrongmngd)
#   elif defined(_WIN32)
#       define TCSOACAESTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOACAESTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACAESTRONGMNGDPRIVATE      extern
#   else
#       define TCSOACAESTRONGMNGDEXPORT
#       define TCSOACAESTRONGMNGDGLOBAL       extern
#       define TCSOACAESTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACAESTRONGMNGDEXPORT       __export(tcsoacaestrongmngd)
#       define TCSOACAESTRONGMNGDGLOBAL       extern __global(tcsoacaestrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACAESTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOACAESTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACAESTRONGMNGDEXPORT
#       define TCSOACAESTRONGMNGDGLOBAL       extern
#   endif
#endif

