/*==============================================================================
                Copyright (c) 2003-2005 UGS Corporation
                   Unpublished - All Rights Reserved
 ==============================================================================*/

/*
    File Description:

    The header file that defines the export symbols for the ICSIE library
 */

#include <common/library_indicators.h>



#ifdef EXPORTLIBRARY
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libicsie

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use ICSCOMMON_API, not ICSEXPORT */

#define ICSIE_API ICSIEEXPORT

/* Support ICSEXPORT for autogenerated schema/pif code only */

#if IPLIB == libicsie
#   if defined(__lint)
#       define ICSIEEXPORT       __export(libicsie)
#       define ICSIEGLOBAL       extern __global(libicsie)
#       define ICSIEPRIVATE      extern __private(libicsie)
#   elif defined(_WIN32)
#       define ICSIEEXPORT       __declspec(dllexport)
#       define ICSIEGLOBAL       extern __declspec(dllexport)
#       define ICSIEPRIVATE      extern
#   else
#       define ICSIEEXPORT
#       define ICSIEGLOBAL       extern
#       define ICSIEPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define ICSIEEXPORT       __export(libicsie)
#       define ICSIEGLOBAL       extern __global(libicsie)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define ICSIEEXPORT       __declspec(dllimport)
#       define ICSIEGLOBAL       extern __declspec(dllimport)
#   else
#       define ICSIEEXPORT
#       define ICSIEGLOBAL       extern
#   endif
#endif
