/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoareportsstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAREPORTSSTRONGMNGD_API, not TCSOAREPORTSSTRONGMNGDEXPORT */

#define TCSOAREPORTSSTRONGMNGD_API TCSOAREPORTSSTRONGMNGDEXPORT

/* Support TCSOAREPORTSSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoareportsstrongmngd
#   if defined(__lint)
#       define TCSOAREPORTSSTRONGMNGDEXPORT       __export(tcsoareportsstrongmngd)
#       define TCSOAREPORTSSTRONGMNGDGLOBAL       extern __global(tcsoareportsstrongmngd)
#       define TCSOAREPORTSSTRONGMNGDPRIVATE      extern __private(tcsoareportsstrongmngd)
#   elif defined(_WIN32)
#       define TCSOAREPORTSSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOAREPORTSSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOAREPORTSSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOAREPORTSSTRONGMNGDEXPORT
#       define TCSOAREPORTSSTRONGMNGDGLOBAL       extern
#       define TCSOAREPORTSSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAREPORTSSTRONGMNGDEXPORT       __export(tcsoareportsstrongmngd)
#       define TCSOAREPORTSSTRONGMNGDGLOBAL       extern __global(tcsoareportsstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAREPORTSSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOAREPORTSSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAREPORTSSTRONGMNGDEXPORT
#       define TCSOAREPORTSSTRONGMNGDGLOBAL       extern
#   endif
#endif

