/*==============================================================================
                Copyright (c) 2003-2005 UGS Corporation
                   Unpublished - All Rights Reserved
 ==============================================================================*/

/*
    File Description:

    The header file that defines the export symbols for the INTERNAL_EXITS library
 */

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libinternal_exits

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use INTERNAL_EXITS_API, not INTERNAL_EXITSEXPORT */

#define INTERNAL_EXITS_API INTERNAL_EXITSEXPORT

/* Support INTERNAL_EXITSEXPORT for autogenerated schema/pif code only */

#if IPLIB==libinternal_exits
#   if defined(__lint)
#       define INTERNAL_EXITSEXPORT       __export(internal_exits)
#       define INTERNAL_EXITSGLOBAL       extern __global(internal_exits)
#       define INTERNAL_EXITSPRIVATE      extern __private(internal_exits)
#   elif defined(_WIN32)
#       define INTERNAL_EXITSEXPORT       __declspec(dllexport)
#       define INTERNAL_EXITSGLOBAL       extern __declspec(dllexport)
#       define INTERNAL_EXITSPRIVATE      extern
#   else
#       define INTERNAL_EXITSEXPORT
#       define INTERNAL_EXITSGLOBAL       extern
#       define INTERNAL_EXITSPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define INTERNAL_EXITSEXPORT       __export(internal_exits)
#       define INTERNAL_EXITSGLOBAL       extern __global(internal_exits)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define INTERNAL_EXITSEXPORT      __declspec(dllimport)
#       define INTERNAL_EXITSGLOBAL       extern __declspec(dllimport)
#   else
#       define INTERNAL_EXITSEXPORT
#       define INTERNAL_EXITSGLOBAL       extern
#   endif
#endif

