/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoacadbomalignmentstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACADBOMALIGNMENTSTRONGMNGD_API, not TCSOACADBOMALIGNMENTSTRONGMNGDEXPORT */

#define TCSOACADBOMALIGNMENTSTRONGMNGD_API TCSOACADBOMALIGNMENTSTRONGMNGDEXPORT

/* Support TCSOACADBOMALIGNMENTSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoacadbomalignmentstrongmngd
#   if defined(__lint)
#       define TCSOACADBOMALIGNMENTSTRONGMNGDEXPORT       __export(tcsoacadbomalignmentstrongmngd)
#       define TCSOACADBOMALIGNMENTSTRONGMNGDGLOBAL       extern __global(tcsoacadbomalignmentstrongmngd)
#       define TCSOACADBOMALIGNMENTSTRONGMNGDPRIVATE      extern __private(tcsoacadbomalignmentstrongmngd)
#   elif defined(_WIN32)
#       define TCSOACADBOMALIGNMENTSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOACADBOMALIGNMENTSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACADBOMALIGNMENTSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOACADBOMALIGNMENTSTRONGMNGDEXPORT
#       define TCSOACADBOMALIGNMENTSTRONGMNGDGLOBAL       extern
#       define TCSOACADBOMALIGNMENTSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACADBOMALIGNMENTSTRONGMNGDEXPORT       __export(tcsoacadbomalignmentstrongmngd)
#       define TCSOACADBOMALIGNMENTSTRONGMNGDGLOBAL       extern __global(tcsoacadbomalignmentstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACADBOMALIGNMENTSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOACADBOMALIGNMENTSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACADBOMALIGNMENTSTRONGMNGDEXPORT
#       define TCSOACADBOMALIGNMENTSTRONGMNGDGLOBAL       extern
#   endif
#endif

