/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoaprojectmanagementstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAPROJECTMANAGEMENTSTRONGMNGD_API, not TCSOAPROJECTMANAGEMENTSTRONGMNGDEXPORT */

#define TCSOAPROJECTMANAGEMENTSTRONGMNGD_API TCSOAPROJECTMANAGEMENTSTRONGMNGDEXPORT

/* Support TCSOAPROJECTMANAGEMENTSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoaprojectmanagementstrongmngd
#   if defined(__lint)
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDEXPORT       __export(tcsoaprojectmanagementstrongmngd)
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDGLOBAL       extern __global(tcsoaprojectmanagementstrongmngd)
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDPRIVATE      extern __private(tcsoaprojectmanagementstrongmngd)
#   elif defined(_WIN32)
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDEXPORT
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDGLOBAL       extern
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDEXPORT       __export(tcsoaprojectmanagementstrongmngd)
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDGLOBAL       extern __global(tcsoaprojectmanagementstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDEXPORT
#       define TCSOAPROJECTMANAGEMENTSTRONGMNGDGLOBAL       extern
#   endif
#endif

