// @<COPYRIGHT_START>@
// ===============================================
// Copyright 2006 UGS Corp. All Rights Reserved.
// ===============================================
// @<COPYRIGHT_END>@


#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#error ExportLibrary is defined to be EXPORTLIBRARY
#endif

#define EXPORTLIBRARY            libgms

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use GMS_API, not GMSEXPORT */

#define GMS_API GMSEXPORT

/* Support GMSEXPORT for autogenerated schema/pif code only */

#if IPLIB==libgms
#   if defined(__lint)
#       define GMSEXPORT       __export(gms)
#       define GMSGLOBAL       extern __global(gms)
#       define GMSPRIVATE      extern __private(gms)
#   elif defined(_WIN32)
#       define GMSEXPORT       __declspec(dllexport)
#       define GMSGLOBAL       extern __declspec(dllexport)
#       define GMSPRIVATE      extern
#   else
#       define GMSEXPORT
#       define GMSGLOBAL       extern
#       define GMSPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define GMSEXPORT       __export(gms)
#       define GMSGLOBAL       extern __global(gms)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define GMSEXPORT      __declspec(dllimport)
#       define GMSGLOBAL       extern __declspec(dllimport)
#   else
#       define GMSEXPORT
#       define GMSGLOBAL       extern
#   endif
#endif

