/*==============================================================================
                Copyright (c) 2003-2005 UGS Corporation
                   Unpublished - All Rights Reserved
 ==============================================================================*/

/*
    File Description:

    The header file that defines the export symbols for the TEXTSRV library
 */

#define libtextsrv               -10086

#ifdef EXPORTLIBRARY
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtextsrv

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TEXTSRV_API, not TEXTSRVEXPORT */

#define TEXTSRV_API TEXTSRVEXPORT

/* Support TEXTSRVEXPORT for autogenerated code only */

#if IPLIB==libtextsrv
#   if defined(__lint)
#       define TEXTSRVEXPORT       __export(textsrv)
#       define TEXTSRVGLOBAL       extern __global(textsrv)
#       define TEXTSRVPRIVATE      extern __private(textsrv)
#   elif defined(_WIN32)
#       define TEXTSRVEXPORT       __declspec(dllexport)
#       define TEXTSRVGLOBAL       extern __declspec(dllexport)
#       define TEXTSRVPRIVATE      extern
#   else
#       define TEXTSRVEXPORT
#       define TEXTSRVGLOBAL       extern
#       define TEXTSRVPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TEXTSRVEXPORT       __export(textsrv)
#       define TEXTSRVGLOBAL       extern __global(textsrv)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TEXTSRVEXPORT      __declspec(dllimport)
#       define TEXTSRVGLOBAL       extern __declspec(dllimport)
#   else
#       define TEXTSRVEXPORT
#       define TEXTSRVGLOBAL       extern
#   endif
#endif
