/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libcba1soacbaextstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use CBA1SOACBAEXTSTRONGMNGD_API, not CBA1SOACBAEXTSTRONGMNGDEXPORT */

#define CBA1SOACBAEXTSTRONGMNGD_API CBA1SOACBAEXTSTRONGMNGDEXPORT

/* Support CBA1SOACBAEXTSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libcba1soacbaextstrongmngd
#   if defined(__lint)
#       define CBA1SOACBAEXTSTRONGMNGDEXPORT       __export(cba1soacbaextstrongmngd)
#       define CBA1SOACBAEXTSTRONGMNGDGLOBAL       extern __global(cba1soacbaextstrongmngd)
#       define CBA1SOACBAEXTSTRONGMNGDPRIVATE      extern __private(cba1soacbaextstrongmngd)
#   elif defined(_WIN32)
#       define CBA1SOACBAEXTSTRONGMNGDEXPORT       __declspec(dllexport)
#       define CBA1SOACBAEXTSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define CBA1SOACBAEXTSTRONGMNGDPRIVATE      extern
#   else
#       define CBA1SOACBAEXTSTRONGMNGDEXPORT
#       define CBA1SOACBAEXTSTRONGMNGDGLOBAL       extern
#       define CBA1SOACBAEXTSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define CBA1SOACBAEXTSTRONGMNGDEXPORT       __export(cba1soacbaextstrongmngd)
#       define CBA1SOACBAEXTSTRONGMNGDGLOBAL       extern __global(cba1soacbaextstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define CBA1SOACBAEXTSTRONGMNGDEXPORT      __declspec(dllimport)
#       define CBA1SOACBAEXTSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define CBA1SOACBAEXTSTRONGMNGDEXPORT
#       define CBA1SOACBAEXTSTRONGMNGDGLOBAL       extern
#   endif
#endif

