/*==============================================================================
                Copyright (c) 2003-2005 UGS Corporation
                   Unpublished - All Rights Reserved
 ==============================================================================*/

/*
    File Description:

    The header file that defines the export symbols for the SERVER_EXITS library
 */

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libserver_exits

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use SERVER_EXITS_API, not SERVER_EXITSEXPORT */

#define SERVER_EXITS_API SERVER_EXITSEXPORT

/* Support SERVER_EXITSEXPORT for autogenerated schema/pif code only */

#if IPLIB==libserver_exits
#   if defined(__lint)
#       define SERVER_EXITSEXPORT       __export(server_exits)
#       define SERVER_EXITSGLOBAL       extern __global(server_exits)
#       define SERVER_EXITSPRIVATE      extern __private(server_exits)
#   elif defined(_WIN32)
#       define SERVER_EXITSEXPORT       __declspec(dllexport)
#       define SERVER_EXITSGLOBAL       extern __declspec(dllexport)
#       define SERVER_EXITSPRIVATE      extern
#   else
#       define SERVER_EXITSEXPORT
#       define SERVER_EXITSGLOBAL       extern
#       define SERVER_EXITSPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define SERVER_EXITSEXPORT       __export(server_exits)
#       define SERVER_EXITSGLOBAL       extern __global(server_exits)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define SERVER_EXITSEXPORT      __declspec(dllimport)
#       define SERVER_EXITSGLOBAL       extern __declspec(dllimport)
#   else
#       define SERVER_EXITSEXPORT
#       define SERVER_EXITSGLOBAL       extern
#   endif
#endif

