
/*=============================================================================
 ===============================================================================
File Description:

    The header file that defines the export symbols for the
    SERVICEEVENTMANAGEMENT library

===============================================================================
Date                     Name                       Description

$HISTORY$
=============================================================================*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libserviceeventmanagement

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use the serviceeventmanagement_API version, not serviceeventmanagementEXPORT */

#define SERVICEEVENTMANAGEMENT_API SERVICEEVENTMANAGEMENTEXPORT

/* Support SERVICEEVENTMANAGEMENTEXPORT for autogenerated schema/pif code only */

#if IPLIB==libserviceeventmanagement
#   if defined(__lint)
#       define SERVICEEVENTMANAGEMENTEXPORT       __export(serviceeventmanagement)
#       define SERVICEEVENTMANAGEMENTGLOBAL       extern __global(serviceeventmanagement)
#       define SERVICEEVENTMANAGEMENTPRIVATE      extern __private(serviceeventmanagement)
#   elif defined(_WIN32)
#       define SERVICEEVENTMANAGEMENTEXPORT       __declspec(dllexport)
#       define SERVICEEVENTMANAGEMENTGLOBAL       extern __declspec(dllexport)
#       define SERVICEEVENTMANAGEMENTPRIVATE      extern
#   else
#       define SERVICEEVENTMANAGEMENTEXPORT
#       define SERVICEEVENTMANAGEMENTGLOBAL       extern
#       define SERVICEEVENTMANAGEMENTPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define SERVICEEVENTMANAGEMENTEXPORT       __export(serviceeventmanagement)
#       define SERVICEEVENTMANAGEMENTGLOBAL       extern __global(serviceeventmanagement)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define SERVICEEVENTMANAGEMENTEXPORT       __declspec(dllimport)
#       define SERVICEEVENTMANAGEMENTGLOBAL       extern __declspec(dllimport)
#   else
#       define SERVICEEVENTMANAGEMENTEXPORT
#       define SERVICEEVENTMANAGEMENTGLOBAL       extern
#   endif
#endif
