/*=============================================================================
                Copyright (c) 1999 Unigraphics Solutions Inc.
                             All rights reserved
===============================================================================
File Description:

     The header file that defines the export symbols for the
     TCSOASERVER library

===============================================================================
Date          Name                   Description
19-Dec-2005  Ron Marchi              initial version
$HISTORY$
=============================================================================*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoaserver

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOASERVER_API, not TCSOASERVEREXPORT */

#define TCSOASERVER_API TCSOASERVEREXPORT

/* Support TCSOASERVEREXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoaserver
#   if defined(__lint)
#       define TCSOASERVEREXPORT       __export(tcsoaserver)
#       define TCSOASERVERGLOBAL       extern __global(tcsoaserver)
#       define TCSOASERVERPRIVATE      extern __private(tcsoaserver)
#   elif defined(_WIN32)
#       define TCSOASERVEREXPORT       __declspec(dllexport)
#       define TCSOASERVERGLOBAL       extern __declspec(dllexport)
#       define TCSOASERVERPRIVATE      extern
#   else
#       define TCSOASERVEREXPORT
#       define TCSOASERVERGLOBAL       extern
#       define TCSOASERVERPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOASERVEREXPORT       __export(tcsoaserver)
#       define TCSOASERVERGLOBAL       extern __global(tcsoaserver)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOASERVEREXPORT      __declspec(dllimport)
#       define TCSOASERVERGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOASERVEREXPORT
#       define TCSOASERVERGLOBAL       extern
#   endif
#endif
