/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoacalendarmanagementstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACALENDARMANAGEMENTSTRONGMNGD_API, not TCSOACALENDARMANAGEMENTSTRONGMNGDEXPORT */

#define TCSOACALENDARMANAGEMENTSTRONGMNGD_API TCSOACALENDARMANAGEMENTSTRONGMNGDEXPORT

/* Support TCSOACALENDARMANAGEMENTSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoacalendarmanagementstrongmngd
#   if defined(__lint)
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDEXPORT       __export(tcsoacalendarmanagementstrongmngd)
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDGLOBAL       extern __global(tcsoacalendarmanagementstrongmngd)
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDPRIVATE      extern __private(tcsoacalendarmanagementstrongmngd)
#   elif defined(_WIN32)
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDEXPORT
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDGLOBAL       extern
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDEXPORT       __export(tcsoacalendarmanagementstrongmngd)
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDGLOBAL       extern __global(tcsoacalendarmanagementstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDEXPORT
#       define TCSOACALENDARMANAGEMENTSTRONGMNGDGLOBAL       extern
#   endif
#endif

