/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libfnd0soaauditmanagerstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use FND0SOAAUDITMANAGERSTRONGMNGD_API, not FND0SOAAUDITMANAGERSTRONGMNGDEXPORT */

#define FND0SOAAUDITMANAGERSTRONGMNGD_API FND0SOAAUDITMANAGERSTRONGMNGDEXPORT

/* Support FND0SOAAUDITMANAGERSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libfnd0soaauditmanagerstrongmngd
#   if defined(__lint)
#       define FND0SOAAUDITMANAGERSTRONGMNGDEXPORT       __export(fnd0soaauditmanagerstrongmngd)
#       define FND0SOAAUDITMANAGERSTRONGMNGDGLOBAL       extern __global(fnd0soaauditmanagerstrongmngd)
#       define FND0SOAAUDITMANAGERSTRONGMNGDPRIVATE      extern __private(fnd0soaauditmanagerstrongmngd)
#   elif defined(_WIN32)
#       define FND0SOAAUDITMANAGERSTRONGMNGDEXPORT       __declspec(dllexport)
#       define FND0SOAAUDITMANAGERSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define FND0SOAAUDITMANAGERSTRONGMNGDPRIVATE      extern
#   else
#       define FND0SOAAUDITMANAGERSTRONGMNGDEXPORT
#       define FND0SOAAUDITMANAGERSTRONGMNGDGLOBAL       extern
#       define FND0SOAAUDITMANAGERSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define FND0SOAAUDITMANAGERSTRONGMNGDEXPORT       __export(fnd0soaauditmanagerstrongmngd)
#       define FND0SOAAUDITMANAGERSTRONGMNGDGLOBAL       extern __global(fnd0soaauditmanagerstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define FND0SOAAUDITMANAGERSTRONGMNGDEXPORT      __declspec(dllimport)
#       define FND0SOAAUDITMANAGERSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define FND0SOAAUDITMANAGERSTRONGMNGDEXPORT
#       define FND0SOAAUDITMANAGERSTRONGMNGDGLOBAL       extern
#   endif
#endif

