/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libfdp0soafourdplanningstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use FDP0SOAFOURDPLANNINGSTRONGMNGD_API, not FDP0SOAFOURDPLANNINGSTRONGMNGDEXPORT */

#define FDP0SOAFOURDPLANNINGSTRONGMNGD_API FDP0SOAFOURDPLANNINGSTRONGMNGDEXPORT

/* Support FDP0SOAFOURDPLANNINGSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libfdp0soafourdplanningstrongmngd
#   if defined(__lint)
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDEXPORT       __export(fdp0soafourdplanningstrongmngd)
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDGLOBAL       extern __global(fdp0soafourdplanningstrongmngd)
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDPRIVATE      extern __private(fdp0soafourdplanningstrongmngd)
#   elif defined(_WIN32)
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDEXPORT       __declspec(dllexport)
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDPRIVATE      extern
#   else
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDEXPORT
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDGLOBAL       extern
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDEXPORT       __export(fdp0soafourdplanningstrongmngd)
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDGLOBAL       extern __global(fdp0soafourdplanningstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDEXPORT      __declspec(dllimport)
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDEXPORT
#       define FDP0SOAFOURDPLANNINGSTRONGMNGDGLOBAL       extern
#   endif
#endif

