/*==============================================================================
                Copyright (c) 2003-2005 UGS Corporation
                   Unpublished - All Rights Reserved
 ==============================================================================*/

/*
    File Description:

    The header file that defines the export symbols for the NXMGR_IM library
 */

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libnxmgr_im

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use NXMGR_IM_API, not NXMGR_IMEXPORT */

#define NXMGR_IM_API NXMGR_IMEXPORT

/* Support NXMGR_IMEXPORT for autogenerated schema/pif code only */

#if IPLIB==libnxmgr_im
#   if defined(__lint)
#       define NXMGR_IMEXPORT       __export(nxmgr_im)
#       define NXMGR_IMGLOBAL       extern __global(nxmgr_im)
#       define NXMGR_IMPRIVATE      extern __private(nxmgr_im)
#   elif defined(_WIN32)
#       define NXMGR_IMEXPORT       __declspec(dllexport)
#       define NXMGR_IMGLOBAL       extern __declspec(dllexport)
#       define NXMGR_IMPRIVATE      extern
#   else
#       define NXMGR_IMEXPORT
#       define NXMGR_IMGLOBAL       extern
#       define NXMGR_IMPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define NXMGR_IMEXPORT       __export(nxmgr_im)
#       define NXMGR_IMGLOBAL       extern __global(nxmgr_im)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define NXMGR_IMEXPORT      __declspec(dllimport)
#       define NXMGR_IMGLOBAL       extern __declspec(dllimport)
#   else
#       define NXMGR_IMEXPORT
#       define NXMGR_IMGLOBAL       extern
#   endif
#endif
