/*
   Copyright 2020 Siemens Digital Industries Software
   ==================================================
   Copyright 2016.
   Siemens Product Lifecycle Management Software Inc.
   All Rights Reserved.
   ==================================================
   Copyright 2020 Siemens Digital Industries Software
*/

/**
    @file

    This file undefines the export declarations for the library Fgc0cm4g

    This file should be obsoleted once the autogenerated version is created in out/meta/Fgc0cm4g folder.
    The autogenerated version will be generated after any metamodel operation is defined or overridden
    in the fgc0cm4g template.

*/

#include <common/library_indicators.h>

#if !defined(EXPORTLIBRARY)
#   error EXPORTLIBRARY is not defined
#endif

#undef EXPORTLIBRARY

#if !defined(LIBFGC0CM4G) && !defined(IPLIB)
#   error IPLIB or LIBFGC0CM4G is not defined
#endif

#undef FGC0CM4G_API
#undef FGC0CM4GEXPORT
#undef FGC0CM4GGLOBAL
#undef FGC0CM4GPRIVATE
