// @<COPYRIGHT_START>@
// ===============================================
// Copyright 2006 UGS Corp. All Rights Reserved.
// ===============================================
// @<COPYRIGHT_END>@

/** 
    @file 

    Define exports for libbob.
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY          libbob

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use BOB_API, not BOBEXPORT */

#define BOB_API BOBEXPORT

/* Support BOBEXPORT for autogenerated schema/pif code only */

#if IPLIB==libbob
#   if defined(__lint)
#       define BOBEXPORT       __export(bob)
#       define BOBGLOBAL       extern __global(bob)
#       define BOBPRIVATE      extern __private(bob)
#   elif defined(_WIN32)
#       define BOBEXPORT       __declspec(dllexport)
#       define BOBGLOBAL       extern __declspec(dllexport)
#       define BOBPRIVATE      extern
#   else
#       define BOBEXPORT
#       define BOBGLOBAL       extern
#       define BOBPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define BOBEXPORT       __export(bob)
#       define BOBGLOBAL       extern __global(bob)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define BOBEXPORT      __declspec(dllimport)
#       define BOBGLOBAL       extern __declspec(dllimport)
#   else
#       define BOBEXPORT
#       define BOBGLOBAL       extern
#   endif
#endif

