// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.0a_p3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:150

#ifndef _TAO_IDL_D__WORKDIR_TC101W0604_64_WNTX64_DRV_SERVER_TCGATEWAY_TCCONSTANTS_C_VL9KNV_H_
#define _TAO_IDL_D__WORKDIR_TC101W0604_64_WNTX64_DRV_SERVER_TCGATEWAY_TCCONSTANTS_C_VL9KNV_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 0 || TAO_BETA_VERSION != 4
#error This file should be regenerated with TAO_IDL from version 2.0a_p3
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO DSPEC_DLL

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_sequence/sequence_ch.cpp:100

#if !defined (_TCBYTESEQ_T_CH_)
#define _TCBYTESEQ_T_CH_

class TcByteSeq_t;

typedef
  ::TAO_FixedSeq_Var_T<
      TcByteSeq_t
    >
  TcByteSeq_t_var;

typedef
  ::TAO_Seq_Out_T<
      TcByteSeq_t
    >
  TcByteSeq_t_out;

class DSPEC_DLL TcByteSeq_t
  : public
      ::TAO::unbounded_value_sequence<
          ::CORBA::Octet
        >
{
public:
  TcByteSeq_t (void);
  TcByteSeq_t ( ::CORBA::ULong max);
  TcByteSeq_t (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    ::CORBA::Octet* buffer, 
    ::CORBA::Boolean release = false);
  TcByteSeq_t (const TcByteSeq_t &);
  virtual ~TcByteSeq_t (void);
  

  // TAO_IDL - Generated from
  // be\be_type.cpp:307
  
  typedef TcByteSeq_t_var _var_type;
  typedef TcByteSeq_t_out _out_type;

  static void _tao_any_destructor (void *);

  

#if (TAO_NO_COPY_OCTET_SEQUENCES == 1)
  TcByteSeq_t (
      ::CORBA::ULong length,
      const ACE_Message_Block* mb
    )
    : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (length, mb) {}
#endif /* TAO_NO_COPY_OCTET_SEQUENCE == 1 */
};

#endif /* end #if !defined */

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcByteSeq_t;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

typedef TcByteSeq_t TcString_t;
typedef TcByteSeq_t_var TcString_t_var;
typedef TcByteSeq_t_out TcString_t_out;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcString_t;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

typedef TcString_t tc_uid_t;
typedef TcString_t_var tc_uid_t_var;
typedef TcString_t_out tc_uid_t_out;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_tc_uid_t;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

typedef TcString_t TcMimeMediaType_t;
typedef TcString_t_var TcMimeMediaType_t_var;
typedef TcString_t_out TcMimeMediaType_t_out;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcMimeMediaType_t;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

typedef TcString_t TcMimeMediaSubtype_t;
typedef TcString_t_var TcMimeMediaSubtype_t_var;
typedef TcString_t_out TcMimeMediaSubtype_t_out;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcMimeMediaSubtype_t;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

typedef TcString_t TcMimeMediaTypeParam_t;
typedef TcString_t_var TcMimeMediaTypeParam_t_var;
typedef TcString_t_out TcMimeMediaTypeParam_t_out;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcMimeMediaTypeParam_t;

// TAO_IDL - Generated from
// be\be_type.cpp:261

struct TcMimeType_s;

typedef
  ::TAO_Var_Var_T<
      TcMimeType_s
    >
  TcMimeType_s_var;

typedef
  ::TAO_Out_T<
      TcMimeType_s
    >
  TcMimeType_s_out;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_structure/structure_ch.cpp:49

struct DSPEC_DLL TcMimeType_s
{

  // TAO_IDL - Generated from
  // be\be_type.cpp:307
  
  typedef TcMimeType_s_var _var_type;
  typedef TcMimeType_s_out _out_type;

  static void _tao_any_destructor (void *);
  
  TcString_t type;
  TcString_t subtype;
  TcString_t parameters;
};

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcMimeType_s;

// TAO_IDL - Generated from
// be\be_type.cpp:261

struct TcPropertySet_s;

typedef
  ::TAO_Var_Var_T<
      TcPropertySet_s
    >
  TcPropertySet_s_var;

typedef
  ::TAO_Out_T<
      TcPropertySet_s
    >
  TcPropertySet_s_out;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_structure/structure_ch.cpp:49

struct DSPEC_DLL TcPropertySet_s
{

  // TAO_IDL - Generated from
  // be\be_type.cpp:307
  
  typedef TcPropertySet_s_var _var_type;
  typedef TcPropertySet_s_out _out_type;

  static void _tao_any_destructor (void *);
  
  TcString_t file_name;
  TcString_t original_file_name;
};

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcPropertySet_s;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:509

typedef TcMimeType_s TcMimeType_t;
typedef TcMimeType_s_var TcMimeType_t_var;
typedef TcMimeType_s_out TcMimeType_t_out;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcMimeType_t;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:509

typedef TcPropertySet_s TcPropertySet_t;
typedef TcPropertySet_s_var TcPropertySet_t_var;
typedef TcPropertySet_s_out TcPropertySet_t_out;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcPropertySet_t;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_sequence/sequence_ch.cpp:100

#if !defined (_TCBUFFERSEQ_T_CH_)
#define _TCBUFFERSEQ_T_CH_

class TcBufferSeq_t;

typedef
  ::TAO_FixedSeq_Var_T<
      TcBufferSeq_t
    >
  TcBufferSeq_t_var;

typedef
  ::TAO_Seq_Out_T<
      TcBufferSeq_t
    >
  TcBufferSeq_t_out;

class DSPEC_DLL TcBufferSeq_t
  : public
      ::TAO::unbounded_value_sequence<
          ::CORBA::Octet
        >
{
public:
  TcBufferSeq_t (void);
  TcBufferSeq_t ( ::CORBA::ULong max);
  TcBufferSeq_t (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    ::CORBA::Octet* buffer, 
    ::CORBA::Boolean release = false);
  TcBufferSeq_t (const TcBufferSeq_t &);
  virtual ~TcBufferSeq_t (void);
  

  // TAO_IDL - Generated from
  // be\be_type.cpp:307
  
  typedef TcBufferSeq_t_var _var_type;
  typedef TcBufferSeq_t_out _out_type;

  static void _tao_any_destructor (void *);

  

#if (TAO_NO_COPY_OCTET_SEQUENCES == 1)
  TcBufferSeq_t (
      ::CORBA::ULong length,
      const ACE_Message_Block* mb
    )
    : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (length, mb) {}
#endif /* TAO_NO_COPY_OCTET_SEQUENCE == 1 */
};

#endif /* end #if !defined */

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcBufferSeq_t;

// TAO_IDL - Generated from
// be\be_type.cpp:261

class TcStringValue_u;

typedef
  ::TAO_Var_Var_T<
      TcStringValue_u
    >
  TcStringValue_u_var;

typedef
  ::TAO_Out_T<
      TcStringValue_u
    >
  TcStringValue_u_out;

class DSPEC_DLL TcStringValue_u
{
public:
  TcStringValue_u (void);
  TcStringValue_u (const TcStringValue_u &);
  ~TcStringValue_u (void);

  TcStringValue_u &operator= (const TcStringValue_u &);

  // TAO_IDL - Generated from
  // d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_union/discriminant_ch.cpp:107

  void _d ( ::CORBA::Boolean);
  ::CORBA::Boolean _d (void) const;

  // TAO_IDL - Generated from
  // be\be_type.cpp:307
  
  typedef TcStringValue_u_var _var_type;
  typedef TcStringValue_u_out _out_type;

  static void _tao_any_destructor (void *);

  // TAO_IDL - Generated from
  // d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_union_branch/public_ch.cpp:549

  void string_value (const TcString_t &);
  const TcString_t &string_value (void) const;
  TcString_t &string_value (void);

  // TAO_IDL - Generated from
  // d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_union/union_ch.cpp:127

  void _default (void);
private:
  ::CORBA::Boolean disc_;

  union
  {
    // TAO_IDL - Generated from
    // d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_union_branch/private_ch.cpp:445
    TcString_t *string_value_;
  } u_;

  /// TAO extension - frees any allocated storage.
  void _reset (void);
};

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcStringValue_u;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:555

typedef TcStringValue_u TcStringValue_t;
typedef TcStringValue_u_var TcStringValue_t_var;
typedef TcStringValue_u_out TcStringValue_t_out;

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

extern DSPEC_DLL ::CORBA::TypeCode_ptr const _tc_TcStringValue_t;

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:679

  template<>
  class Arg_Traits< ::TcByteSeq_t>
    : public
        Var_Size_Arg_Traits_T<
            ::TcByteSeq_t,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::TcMimeType_s>
    : public
        Var_Size_Arg_Traits_T<
            ::TcMimeType_s,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::TcPropertySet_s>
    : public
        Var_Size_Arg_Traits_T<
            ::TcPropertySet_s,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:679

  template<>
  class Arg_Traits< ::TcBufferSeq_t>
    : public
        Var_Size_Arg_Traits_T<
            ::TcBufferSeq_t,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be\be_visitor_arg_traits.cpp:1052

  template<>
  class Arg_Traits< ::TcStringValue_u>
    : public
        Var_Size_Arg_Traits_T<
            ::TcStringValue_u,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_sequence/any_op_ch.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

DSPEC_DLL void operator<<= ( ::CORBA::Any &, const TcByteSeq_t &); // copying version
DSPEC_DLL void operator<<= ( ::CORBA::Any &, TcByteSeq_t*); // noncopying version
DSPEC_DLL ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TcByteSeq_t *&); // deprecated
DSPEC_DLL ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TcByteSeq_t *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_structure/any_op_ch.cpp:44


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

DSPEC_DLL void operator<<= (::CORBA::Any &, const TcMimeType_s &); // copying version
DSPEC_DLL void operator<<= (::CORBA::Any &, TcMimeType_s*); // noncopying version
DSPEC_DLL ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TcMimeType_s *&); // deprecated
DSPEC_DLL ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TcMimeType_s *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_structure/any_op_ch.cpp:44


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

DSPEC_DLL void operator<<= (::CORBA::Any &, const TcPropertySet_s &); // copying version
DSPEC_DLL void operator<<= (::CORBA::Any &, TcPropertySet_s*); // noncopying version
DSPEC_DLL ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TcPropertySet_s *&); // deprecated
DSPEC_DLL ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TcPropertySet_s *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_sequence/any_op_ch.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

DSPEC_DLL void operator<<= ( ::CORBA::Any &, const TcBufferSeq_t &); // copying version
DSPEC_DLL void operator<<= ( ::CORBA::Any &, TcBufferSeq_t*); // noncopying version
DSPEC_DLL ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TcBufferSeq_t *&); // deprecated
DSPEC_DLL ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TcBufferSeq_t *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_union/any_op_ch.cpp:44


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

DSPEC_DLL void operator<<= (::CORBA::Any &, const TcStringValue_u &); // copying version
DSPEC_DLL void operator<<= (::CORBA::Any &, TcStringValue_u*); // noncopying version
DSPEC_DLL ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TcStringValue_u *&); // deprecated
DSPEC_DLL ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TcStringValue_u *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_sequence/cdr_op_ch.cpp:61

#if !defined _TAO_CDR_OP_TcByteSeq_t_H_
#define _TAO_CDR_OP_TcByteSeq_t_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


DSPEC_DLL ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TcByteSeq_t &_tao_sequence);
DSPEC_DLL ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TcByteSeq_t &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_TcByteSeq_t_H_ */

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_structure/cdr_op_ch.cpp:45


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

DSPEC_DLL ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TcMimeType_s &);
DSPEC_DLL ::CORBA::Boolean operator>> (TAO_InputCDR &, TcMimeType_s &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_structure/cdr_op_ch.cpp:45


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

DSPEC_DLL ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TcPropertySet_s &);
DSPEC_DLL ::CORBA::Boolean operator>> (TAO_InputCDR &, TcPropertySet_s &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_sequence/cdr_op_ch.cpp:61

#if !defined _TAO_CDR_OP_TcBufferSeq_t_H_
#define _TAO_CDR_OP_TcBufferSeq_t_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


DSPEC_DLL ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TcBufferSeq_t &_tao_sequence);
DSPEC_DLL ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TcBufferSeq_t &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_TcBufferSeq_t_H_ */

// TAO_IDL - Generated from
// d:\_tao_work\ace_wrappers_dynamic_x64_release_vc10\ace_wrappers\tao\tao_idl\be\be_visitor_union/cdr_op_ch.cpp:45


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

DSPEC_DLL ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TcStringValue_u &);
DSPEC_DLL ::CORBA::Boolean operator>> (TAO_InputCDR &, TcStringValue_u &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be\be_codegen.cpp:1581
#if defined (__ACE_INLINE__)
#include "tcconstants_c.i"
#endif /* defined INLINE */

#endif /* ifndef */

