/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoabusinessmodelerstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOABUSINESSMODELERSTRONGMNGD_API, not TCSOABUSINESSMODELERSTRONGMNGDEXPORT */

#define TCSOABUSINESSMODELERSTRONGMNGD_API TCSOABUSINESSMODELERSTRONGMNGDEXPORT

/* Support TCSOABUSINESSMODELERSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoabusinessmodelerstrongmngd
#   if defined(__lint)
#       define TCSOABUSINESSMODELERSTRONGMNGDEXPORT       __export(tcsoabusinessmodelerstrongmngd)
#       define TCSOABUSINESSMODELERSTRONGMNGDGLOBAL       extern __global(tcsoabusinessmodelerstrongmngd)
#       define TCSOABUSINESSMODELERSTRONGMNGDPRIVATE      extern __private(tcsoabusinessmodelerstrongmngd)
#   elif defined(_WIN32)
#       define TCSOABUSINESSMODELERSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOABUSINESSMODELERSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOABUSINESSMODELERSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOABUSINESSMODELERSTRONGMNGDEXPORT
#       define TCSOABUSINESSMODELERSTRONGMNGDGLOBAL       extern
#       define TCSOABUSINESSMODELERSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOABUSINESSMODELERSTRONGMNGDEXPORT       __export(tcsoabusinessmodelerstrongmngd)
#       define TCSOABUSINESSMODELERSTRONGMNGDGLOBAL       extern __global(tcsoabusinessmodelerstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOABUSINESSMODELERSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOABUSINESSMODELERSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOABUSINESSMODELERSTRONGMNGDEXPORT
#       define TCSOABUSINESSMODELERSTRONGMNGDGLOBAL       extern
#   endif
#endif

