/*==============================================================================
                 Copyright 2006 UGS Corp. All Rights Reserved.
==============================================================================*/

/**
    @file

    The header file that defines the export symbols for the
    TCSOACLIENT library

*/
/*  */


#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoaclientmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACLIENTMNGD_API, not TCSOACLIENTEXPORT */

#define TCSOACLIENTMNGD_API TCSOACLIENTMNGDEXPORT

/* Support TCSOACLIENTEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoaclientmngd
#   if defined(__lint)
#       define TCSOACLIENTMNGDEXPORT       __export(tcsoaclientmngd)
#       define TCSOACLIENTMNGDGLOBAL       extern __global(tcsoaclientmngd)
#       define TCSOACLIENTMNGDPRIVATE      extern __private(tcsoaclientmngd)
#   elif defined(_WIN32)
#       define TCSOACLIENTMNGDEXPORT       __declspec(dllexport)
#       define TCSOACLIENTMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACLIENTMNGDPRIVATE      extern
#   else
#       define TCSOACLIENTMNGDEXPORT
#       define TCSOACLIENTMNGDGLOBAL       extern
#       define TCSOACLIENTMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACLIENTMNGDEXPORT       __export(tcsoaclientmngd)
#       define TCSOACLIENTMNGDGLOBAL       extern __global(tcsoaclientmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACLIENTMNGDEXPORT       __declspec(dllimport)
#       define TCSOACLIENTMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACLIENTMNGDEXPORT
#       define TCSOACLIENTMNGDGLOBAL       extern
#   endif
#endif


