/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoacommon

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use CLIENTCONTEXT_API, not CLIENTCONTEXTEXPORT */

#define CLIENTCONTEXT_API CLIENTCONTEXTEXPORT

/* Support CLIENTCONTEXTEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoacommon
#   if defined(__lint)
#       define CLIENTCONTEXTEXPORT       __export(tcsoacommon)
#       define CLIENTCONTEXTGLOBAL       extern __global(tcsoacommon)
#       define CLIENTCONTEXTPRIVATE      extern __private(tcsoacommon)
#   elif defined(_WIN32)
#       define CLIENTCONTEXTEXPORT       __declspec(dllexport)
#       define CLIENTCONTEXTGLOBAL       extern __declspec(dllexport)
#       define CLIENTCONTEXTPRIVATE      extern
#   else
#       define CLIENTCONTEXTEXPORT
#       define CLIENTCONTEXTGLOBAL       extern
#       define CLIENTCONTEXTPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define CLIENTCONTEXTEXPORT       __export(tcsoacommon)
#       define CLIENTCONTEXTGLOBAL       extern __global(tcsoacommon)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define CLIENTCONTEXTEXPORT      __declspec(dllimport)
#       define CLIENTCONTEXTGLOBAL       extern __declspec(dllimport)
#   else
#       define CLIENTCONTEXTEXPORT
#       define CLIENTCONTEXTGLOBAL       extern
#   endif
#endif

