/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodeladsfoundationmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAADSFOUNDATIONMODELMNGD_API, not TCSOAADSFOUNDATIONMODELMNGDEXPORT */

#define TCSOAADSFOUNDATIONMODELMNGD_API TCSOAADSFOUNDATIONMODELMNGDEXPORT

/* Support TCSOAADSFOUNDATIONMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodeladsfoundationmngd
#   if defined(__lint)
#       define TCSOAADSFOUNDATIONMODELMNGDEXPORT       __export(tcsoamodeladsfoundationmngd)
#       define TCSOAADSFOUNDATIONMODELMNGDGLOBAL       extern __global(tcsoamodeladsfoundationmngd)
#       define TCSOAADSFOUNDATIONMODELMNGDPRIVATE      extern __private(tcsoamodeladsfoundationmngd)
#   elif defined(_WIN32)
#       define TCSOAADSFOUNDATIONMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOAADSFOUNDATIONMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOAADSFOUNDATIONMODELMNGDPRIVATE      extern
#   else
#       define TCSOAADSFOUNDATIONMODELMNGDEXPORT
#       define TCSOAADSFOUNDATIONMODELMNGDGLOBAL       extern
#       define TCSOAADSFOUNDATIONMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAADSFOUNDATIONMODELMNGDEXPORT       __export(tcsoamodeladsfoundationmngd)
#       define TCSOAADSFOUNDATIONMODELMNGDGLOBAL       extern __global(tcsoamodeladsfoundationmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAADSFOUNDATIONMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOAADSFOUNDATIONMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAADSFOUNDATIONMODELMNGDEXPORT
#       define TCSOAADSFOUNDATIONMODELMNGDGLOBAL       extern
#   endif
#endif

