/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelbrndmgmtmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOABRNDMGMTMODELMNGD_API, not TCSOABRNDMGMTMODELMNGDEXPORT */

#define TCSOABRNDMGMTMODELMNGD_API TCSOABRNDMGMTMODELMNGDEXPORT

/* Support TCSOABRNDMGMTMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelbrndmgmtmngd
#   if defined(__lint)
#       define TCSOABRNDMGMTMODELMNGDEXPORT       __export(tcsoamodelbrndmgmtmngd)
#       define TCSOABRNDMGMTMODELMNGDGLOBAL       extern __global(tcsoamodelbrndmgmtmngd)
#       define TCSOABRNDMGMTMODELMNGDPRIVATE      extern __private(tcsoamodelbrndmgmtmngd)
#   elif defined(_WIN32)
#       define TCSOABRNDMGMTMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOABRNDMGMTMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOABRNDMGMTMODELMNGDPRIVATE      extern
#   else
#       define TCSOABRNDMGMTMODELMNGDEXPORT
#       define TCSOABRNDMGMTMODELMNGDGLOBAL       extern
#       define TCSOABRNDMGMTMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOABRNDMGMTMODELMNGDEXPORT       __export(tcsoamodelbrndmgmtmngd)
#       define TCSOABRNDMGMTMODELMNGDGLOBAL       extern __global(tcsoamodelbrndmgmtmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOABRNDMGMTMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOABRNDMGMTMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOABRNDMGMTMODELMNGDEXPORT
#       define TCSOABRNDMGMTMODELMNGDGLOBAL       extern
#   endif
#endif

