/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelcbaextmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACBAEXTMODELMNGD_API, not TCSOACBAEXTMODELMNGDEXPORT */

#define TCSOACBAEXTMODELMNGD_API TCSOACBAEXTMODELMNGDEXPORT

/* Support TCSOACBAEXTMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelcbaextmngd
#   if defined(__lint)
#       define TCSOACBAEXTMODELMNGDEXPORT       __export(tcsoamodelcbaextmngd)
#       define TCSOACBAEXTMODELMNGDGLOBAL       extern __global(tcsoamodelcbaextmngd)
#       define TCSOACBAEXTMODELMNGDPRIVATE      extern __private(tcsoamodelcbaextmngd)
#   elif defined(_WIN32)
#       define TCSOACBAEXTMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOACBAEXTMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACBAEXTMODELMNGDPRIVATE      extern
#   else
#       define TCSOACBAEXTMODELMNGDEXPORT
#       define TCSOACBAEXTMODELMNGDGLOBAL       extern
#       define TCSOACBAEXTMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACBAEXTMODELMNGDEXPORT       __export(tcsoamodelcbaextmngd)
#       define TCSOACBAEXTMODELMNGDGLOBAL       extern __global(tcsoamodelcbaextmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACBAEXTMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOACBAEXTMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACBAEXTMODELMNGDEXPORT
#       define TCSOACBAEXTMODELMNGDGLOBAL       extern
#   endif
#endif

