/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelcbamngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACBAMODELMNGD_API, not TCSOACBAMODELMNGDEXPORT */

#define TCSOACBAMODELMNGD_API TCSOACBAMODELMNGDEXPORT

/* Support TCSOACBAMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelcbamngd
#   if defined(__lint)
#       define TCSOACBAMODELMNGDEXPORT       __export(tcsoamodelcbamngd)
#       define TCSOACBAMODELMNGDGLOBAL       extern __global(tcsoamodelcbamngd)
#       define TCSOACBAMODELMNGDPRIVATE      extern __private(tcsoamodelcbamngd)
#   elif defined(_WIN32)
#       define TCSOACBAMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOACBAMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACBAMODELMNGDPRIVATE      extern
#   else
#       define TCSOACBAMODELMNGDEXPORT
#       define TCSOACBAMODELMNGDGLOBAL       extern
#       define TCSOACBAMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACBAMODELMNGDEXPORT       __export(tcsoamodelcbamngd)
#       define TCSOACBAMODELMNGDGLOBAL       extern __global(tcsoamodelcbamngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACBAMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOACBAMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACBAMODELMNGDEXPORT
#       define TCSOACBAMODELMNGDGLOBAL       extern
#   endif
#endif

