/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelcmmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACMMODELMNGD_API, not TCSOACMMODELMNGDEXPORT */

#define TCSOACMMODELMNGD_API TCSOACMMODELMNGDEXPORT

/* Support TCSOACMMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelcmmngd
#   if defined(__lint)
#       define TCSOACMMODELMNGDEXPORT       __export(tcsoamodelcmmngd)
#       define TCSOACMMODELMNGDGLOBAL       extern __global(tcsoamodelcmmngd)
#       define TCSOACMMODELMNGDPRIVATE      extern __private(tcsoamodelcmmngd)
#   elif defined(_WIN32)
#       define TCSOACMMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOACMMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACMMODELMNGDPRIVATE      extern
#   else
#       define TCSOACMMODELMNGDEXPORT
#       define TCSOACMMODELMNGDGLOBAL       extern
#       define TCSOACMMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACMMODELMNGDEXPORT       __export(tcsoamodelcmmngd)
#       define TCSOACMMODELMNGDGLOBAL       extern __global(tcsoamodelcmmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACMMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOACMMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACMMODELMNGDEXPORT
#       define TCSOACMMODELMNGDGLOBAL       extern
#   endif
#endif

