/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelcmtmesintegmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACMTMESINTEGMODELMNGD_API, not TCSOACMTMESINTEGMODELMNGDEXPORT */

#define TCSOACMTMESINTEGMODELMNGD_API TCSOACMTMESINTEGMODELMNGDEXPORT

/* Support TCSOACMTMESINTEGMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelcmtmesintegmngd
#   if defined(__lint)
#       define TCSOACMTMESINTEGMODELMNGDEXPORT       __export(tcsoamodelcmtmesintegmngd)
#       define TCSOACMTMESINTEGMODELMNGDGLOBAL       extern __global(tcsoamodelcmtmesintegmngd)
#       define TCSOACMTMESINTEGMODELMNGDPRIVATE      extern __private(tcsoamodelcmtmesintegmngd)
#   elif defined(_WIN32)
#       define TCSOACMTMESINTEGMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOACMTMESINTEGMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACMTMESINTEGMODELMNGDPRIVATE      extern
#   else
#       define TCSOACMTMESINTEGMODELMNGDEXPORT
#       define TCSOACMTMESINTEGMODELMNGDGLOBAL       extern
#       define TCSOACMTMESINTEGMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACMTMESINTEGMODELMNGDEXPORT       __export(tcsoamodelcmtmesintegmngd)
#       define TCSOACMTMESINTEGMODELMNGDGLOBAL       extern __global(tcsoamodelcmtmesintegmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACMTMESINTEGMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOACMTMESINTEGMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACMTMESINTEGMODELMNGDEXPORT
#       define TCSOACMTMESINTEGMODELMNGDGLOBAL       extern
#   endif
#endif

