/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelcmtpadtwpmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACMTPADTWPMODELMNGD_API, not TCSOACMTPADTWPMODELMNGDEXPORT */

#define TCSOACMTPADTWPMODELMNGD_API TCSOACMTPADTWPMODELMNGDEXPORT

/* Support TCSOACMTPADTWPMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelcmtpadtwpmngd
#   if defined(__lint)
#       define TCSOACMTPADTWPMODELMNGDEXPORT       __export(tcsoamodelcmtpadtwpmngd)
#       define TCSOACMTPADTWPMODELMNGDGLOBAL       extern __global(tcsoamodelcmtpadtwpmngd)
#       define TCSOACMTPADTWPMODELMNGDPRIVATE      extern __private(tcsoamodelcmtpadtwpmngd)
#   elif defined(_WIN32)
#       define TCSOACMTPADTWPMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOACMTPADTWPMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACMTPADTWPMODELMNGDPRIVATE      extern
#   else
#       define TCSOACMTPADTWPMODELMNGDEXPORT
#       define TCSOACMTPADTWPMODELMNGDGLOBAL       extern
#       define TCSOACMTPADTWPMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACMTPADTWPMODELMNGDEXPORT       __export(tcsoamodelcmtpadtwpmngd)
#       define TCSOACMTPADTWPMODELMNGDGLOBAL       extern __global(tcsoamodelcmtpadtwpmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACMTPADTWPMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOACMTPADTWPMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACMTPADTWPMODELMNGDEXPORT
#       define TCSOACMTPADTWPMODELMNGDGLOBAL       extern
#   endif
#endif

