/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelcontmgmts1000dmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACONTMGMTS1000DMODELMNGD_API, not TCSOACONTMGMTS1000DMODELMNGDEXPORT */

#define TCSOACONTMGMTS1000DMODELMNGD_API TCSOACONTMGMTS1000DMODELMNGDEXPORT

/* Support TCSOACONTMGMTS1000DMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelcontmgmts1000dmngd
#   if defined(__lint)
#       define TCSOACONTMGMTS1000DMODELMNGDEXPORT       __export(tcsoamodelcontmgmts1000dmngd)
#       define TCSOACONTMGMTS1000DMODELMNGDGLOBAL       extern __global(tcsoamodelcontmgmts1000dmngd)
#       define TCSOACONTMGMTS1000DMODELMNGDPRIVATE      extern __private(tcsoamodelcontmgmts1000dmngd)
#   elif defined(_WIN32)
#       define TCSOACONTMGMTS1000DMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOACONTMGMTS1000DMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACONTMGMTS1000DMODELMNGDPRIVATE      extern
#   else
#       define TCSOACONTMGMTS1000DMODELMNGDEXPORT
#       define TCSOACONTMGMTS1000DMODELMNGDGLOBAL       extern
#       define TCSOACONTMGMTS1000DMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACONTMGMTS1000DMODELMNGDEXPORT       __export(tcsoamodelcontmgmts1000dmngd)
#       define TCSOACONTMGMTS1000DMODELMNGDGLOBAL       extern __global(tcsoamodelcontmgmts1000dmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACONTMGMTS1000DMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOACONTMGMTS1000DMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACONTMGMTS1000DMODELMNGDEXPORT
#       define TCSOACONTMGMTS1000DMODELMNGDGLOBAL       extern
#   endif
#endif

