/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelcontmgmtditamngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACONTMGMTDITAMODELMNGD_API, not TCSOACONTMGMTDITAMODELMNGDEXPORT */

#define TCSOACONTMGMTDITAMODELMNGD_API TCSOACONTMGMTDITAMODELMNGDEXPORT

/* Support TCSOACONTMGMTDITAMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelcontmgmtditamngd
#   if defined(__lint)
#       define TCSOACONTMGMTDITAMODELMNGDEXPORT       __export(tcsoamodelcontmgmtditamngd)
#       define TCSOACONTMGMTDITAMODELMNGDGLOBAL       extern __global(tcsoamodelcontmgmtditamngd)
#       define TCSOACONTMGMTDITAMODELMNGDPRIVATE      extern __private(tcsoamodelcontmgmtditamngd)
#   elif defined(_WIN32)
#       define TCSOACONTMGMTDITAMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOACONTMGMTDITAMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACONTMGMTDITAMODELMNGDPRIVATE      extern
#   else
#       define TCSOACONTMGMTDITAMODELMNGDEXPORT
#       define TCSOACONTMGMTDITAMODELMNGDGLOBAL       extern
#       define TCSOACONTMGMTDITAMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACONTMGMTDITAMODELMNGDEXPORT       __export(tcsoamodelcontmgmtditamngd)
#       define TCSOACONTMGMTDITAMODELMNGDGLOBAL       extern __global(tcsoamodelcontmgmtditamngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACONTMGMTDITAMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOACONTMGMTDITAMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACONTMGMTDITAMODELMNGDEXPORT
#       define TCSOACONTMGMTDITAMODELMNGDGLOBAL       extern
#   endif
#endif

