/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelcontmgmts1000d40mngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACONTMGMTS1000D40MODELMNGD_API, not TCSOACONTMGMTS1000D40MODELMNGDEXPORT */

#define TCSOACONTMGMTS1000D40MODELMNGD_API TCSOACONTMGMTS1000D40MODELMNGDEXPORT

/* Support TCSOACONTMGMTS1000D40MODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelcontmgmts1000d40mngd
#   if defined(__lint)
#       define TCSOACONTMGMTS1000D40MODELMNGDEXPORT       __export(tcsoamodelcontmgmts1000d40mngd)
#       define TCSOACONTMGMTS1000D40MODELMNGDGLOBAL       extern __global(tcsoamodelcontmgmts1000d40mngd)
#       define TCSOACONTMGMTS1000D40MODELMNGDPRIVATE      extern __private(tcsoamodelcontmgmts1000d40mngd)
#   elif defined(_WIN32)
#       define TCSOACONTMGMTS1000D40MODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOACONTMGMTS1000D40MODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACONTMGMTS1000D40MODELMNGDPRIVATE      extern
#   else
#       define TCSOACONTMGMTS1000D40MODELMNGDEXPORT
#       define TCSOACONTMGMTS1000D40MODELMNGDGLOBAL       extern
#       define TCSOACONTMGMTS1000D40MODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACONTMGMTS1000D40MODELMNGDEXPORT       __export(tcsoamodelcontmgmts1000d40mngd)
#       define TCSOACONTMGMTS1000D40MODELMNGDGLOBAL       extern __global(tcsoamodelcontmgmts1000d40mngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACONTMGMTS1000D40MODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOACONTMGMTS1000D40MODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACONTMGMTS1000D40MODELMNGDEXPORT
#       define TCSOACONTMGMTS1000D40MODELMNGDGLOBAL       extern
#   endif
#endif

