/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelcpdmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACPDMODELMNGD_API, not TCSOACPDMODELMNGDEXPORT */

#define TCSOACPDMODELMNGD_API TCSOACPDMODELMNGDEXPORT

/* Support TCSOACPDMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelcpdmngd
#   if defined(__lint)
#       define TCSOACPDMODELMNGDEXPORT       __export(tcsoamodelcpdmngd)
#       define TCSOACPDMODELMNGDGLOBAL       extern __global(tcsoamodelcpdmngd)
#       define TCSOACPDMODELMNGDPRIVATE      extern __private(tcsoamodelcpdmngd)
#   elif defined(_WIN32)
#       define TCSOACPDMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOACPDMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACPDMODELMNGDPRIVATE      extern
#   else
#       define TCSOACPDMODELMNGDEXPORT
#       define TCSOACPDMODELMNGDGLOBAL       extern
#       define TCSOACPDMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACPDMODELMNGDEXPORT       __export(tcsoamodelcpdmngd)
#       define TCSOACPDMODELMNGDGLOBAL       extern __global(tcsoamodelcpdmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACPDMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOACPDMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACPDMODELMNGDEXPORT
#       define TCSOACPDMODELMNGDGLOBAL       extern
#   endif
#endif

