/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelcpgmaterialsmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACPGMATERIALSMODELMNGD_API, not TCSOACPGMATERIALSMODELMNGDEXPORT */

#define TCSOACPGMATERIALSMODELMNGD_API TCSOACPGMATERIALSMODELMNGDEXPORT

/* Support TCSOACPGMATERIALSMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelcpgmaterialsmngd
#   if defined(__lint)
#       define TCSOACPGMATERIALSMODELMNGDEXPORT       __export(tcsoamodelcpgmaterialsmngd)
#       define TCSOACPGMATERIALSMODELMNGDGLOBAL       extern __global(tcsoamodelcpgmaterialsmngd)
#       define TCSOACPGMATERIALSMODELMNGDPRIVATE      extern __private(tcsoamodelcpgmaterialsmngd)
#   elif defined(_WIN32)
#       define TCSOACPGMATERIALSMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOACPGMATERIALSMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACPGMATERIALSMODELMNGDPRIVATE      extern
#   else
#       define TCSOACPGMATERIALSMODELMNGDEXPORT
#       define TCSOACPGMATERIALSMODELMNGDGLOBAL       extern
#       define TCSOACPGMATERIALSMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACPGMATERIALSMODELMNGDEXPORT       __export(tcsoamodelcpgmaterialsmngd)
#       define TCSOACPGMATERIALSMODELMNGDGLOBAL       extern __global(tcsoamodelcpgmaterialsmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACPGMATERIALSMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOACPGMATERIALSMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACPGMATERIALSMODELMNGDEXPORT
#       define TCSOACPGMATERIALSMODELMNGDGLOBAL       extern
#   endif
#endif

