/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodeldpvmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOADPVMODELMNGD_API, not TCSOADPVMODELMNGDEXPORT */

#define TCSOADPVMODELMNGD_API TCSOADPVMODELMNGDEXPORT

/* Support TCSOADPVMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodeldpvmngd
#   if defined(__lint)
#       define TCSOADPVMODELMNGDEXPORT       __export(tcsoamodeldpvmngd)
#       define TCSOADPVMODELMNGDGLOBAL       extern __global(tcsoamodeldpvmngd)
#       define TCSOADPVMODELMNGDPRIVATE      extern __private(tcsoamodeldpvmngd)
#   elif defined(_WIN32)
#       define TCSOADPVMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOADPVMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOADPVMODELMNGDPRIVATE      extern
#   else
#       define TCSOADPVMODELMNGDEXPORT
#       define TCSOADPVMODELMNGDGLOBAL       extern
#       define TCSOADPVMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOADPVMODELMNGDEXPORT       __export(tcsoamodeldpvmngd)
#       define TCSOADPVMODELMNGDGLOBAL       extern __global(tcsoamodeldpvmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOADPVMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOADPVMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOADPVMODELMNGDEXPORT
#       define TCSOADPVMODELMNGDGLOBAL       extern
#   endif
#endif

