/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodeledaservermngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAEDASERVERMODELMNGD_API, not TCSOAEDASERVERMODELMNGDEXPORT */

#define TCSOAEDASERVERMODELMNGD_API TCSOAEDASERVERMODELMNGDEXPORT

/* Support TCSOAEDASERVERMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodeledaservermngd
#   if defined(__lint)
#       define TCSOAEDASERVERMODELMNGDEXPORT       __export(tcsoamodeledaservermngd)
#       define TCSOAEDASERVERMODELMNGDGLOBAL       extern __global(tcsoamodeledaservermngd)
#       define TCSOAEDASERVERMODELMNGDPRIVATE      extern __private(tcsoamodeledaservermngd)
#   elif defined(_WIN32)
#       define TCSOAEDASERVERMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOAEDASERVERMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOAEDASERVERMODELMNGDPRIVATE      extern
#   else
#       define TCSOAEDASERVERMODELMNGDEXPORT
#       define TCSOAEDASERVERMODELMNGDGLOBAL       extern
#       define TCSOAEDASERVERMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAEDASERVERMODELMNGDEXPORT       __export(tcsoamodeledaservermngd)
#       define TCSOAEDASERVERMODELMNGDGLOBAL       extern __global(tcsoamodeledaservermngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAEDASERVERMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOAEDASERVERMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAEDASERVERMODELMNGDEXPORT
#       define TCSOAEDASERVERMODELMNGDGLOBAL       extern
#   endif
#endif

