/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelfpmgmtmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAFPMGMTMODELMNGD_API, not TCSOAFPMGMTMODELMNGDEXPORT */

#define TCSOAFPMGMTMODELMNGD_API TCSOAFPMGMTMODELMNGDEXPORT

/* Support TCSOAFPMGMTMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelfpmgmtmngd
#   if defined(__lint)
#       define TCSOAFPMGMTMODELMNGDEXPORT       __export(tcsoamodelfpmgmtmngd)
#       define TCSOAFPMGMTMODELMNGDGLOBAL       extern __global(tcsoamodelfpmgmtmngd)
#       define TCSOAFPMGMTMODELMNGDPRIVATE      extern __private(tcsoamodelfpmgmtmngd)
#   elif defined(_WIN32)
#       define TCSOAFPMGMTMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOAFPMGMTMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOAFPMGMTMODELMNGDPRIVATE      extern
#   else
#       define TCSOAFPMGMTMODELMNGDEXPORT
#       define TCSOAFPMGMTMODELMNGDGLOBAL       extern
#       define TCSOAFPMGMTMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAFPMGMTMODELMNGDEXPORT       __export(tcsoamodelfpmgmtmngd)
#       define TCSOAFPMGMTMODELMNGDGLOBAL       extern __global(tcsoamodelfpmgmtmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAFPMGMTMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOAFPMGMTMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAFPMGMTMODELMNGDEXPORT
#       define TCSOAFPMGMTMODELMNGDGLOBAL       extern
#   endif
#endif

