/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelpenetrationmgmtmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAPENETRATIONMGMTMODELMNGD_API, not TCSOAPENETRATIONMGMTMODELMNGDEXPORT */

#define TCSOAPENETRATIONMGMTMODELMNGD_API TCSOAPENETRATIONMGMTMODELMNGDEXPORT

/* Support TCSOAPENETRATIONMGMTMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelpenetrationmgmtmngd
#   if defined(__lint)
#       define TCSOAPENETRATIONMGMTMODELMNGDEXPORT       __export(tcsoamodelpenetrationmgmtmngd)
#       define TCSOAPENETRATIONMGMTMODELMNGDGLOBAL       extern __global(tcsoamodelpenetrationmgmtmngd)
#       define TCSOAPENETRATIONMGMTMODELMNGDPRIVATE      extern __private(tcsoamodelpenetrationmgmtmngd)
#   elif defined(_WIN32)
#       define TCSOAPENETRATIONMGMTMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOAPENETRATIONMGMTMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOAPENETRATIONMGMTMODELMNGDPRIVATE      extern
#   else
#       define TCSOAPENETRATIONMGMTMODELMNGDEXPORT
#       define TCSOAPENETRATIONMGMTMODELMNGDGLOBAL       extern
#       define TCSOAPENETRATIONMGMTMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAPENETRATIONMGMTMODELMNGDEXPORT       __export(tcsoamodelpenetrationmgmtmngd)
#       define TCSOAPENETRATIONMGMTMODELMNGDGLOBAL       extern __global(tcsoamodelpenetrationmgmtmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAPENETRATIONMGMTMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOAPENETRATIONMGMTMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAPENETRATIONMGMTMODELMNGDEXPORT
#       define TCSOAPENETRATIONMGMTMODELMNGDGLOBAL       extern
#   endif
#endif

