/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelpkgartmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAPKGARTMODELMNGD_API, not TCSOAPKGARTMODELMNGDEXPORT */

#define TCSOAPKGARTMODELMNGD_API TCSOAPKGARTMODELMNGDEXPORT

/* Support TCSOAPKGARTMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelpkgartmngd
#   if defined(__lint)
#       define TCSOAPKGARTMODELMNGDEXPORT       __export(tcsoamodelpkgartmngd)
#       define TCSOAPKGARTMODELMNGDGLOBAL       extern __global(tcsoamodelpkgartmngd)
#       define TCSOAPKGARTMODELMNGDPRIVATE      extern __private(tcsoamodelpkgartmngd)
#   elif defined(_WIN32)
#       define TCSOAPKGARTMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOAPKGARTMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOAPKGARTMODELMNGDPRIVATE      extern
#   else
#       define TCSOAPKGARTMODELMNGDEXPORT
#       define TCSOAPKGARTMODELMNGDGLOBAL       extern
#       define TCSOAPKGARTMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAPKGARTMODELMNGDEXPORT       __export(tcsoamodelpkgartmngd)
#       define TCSOAPKGARTMODELMNGDGLOBAL       extern __global(tcsoamodelpkgartmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAPKGARTMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOAPKGARTMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAPKGARTMODELMNGDEXPORT
#       define TCSOAPKGARTMODELMNGDGLOBAL       extern
#   endif
#endif

