/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelserviceprocessingmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOASERVICEPROCESSINGMODELMNGD_API, not TCSOASERVICEPROCESSINGMODELMNGDEXPORT */

#define TCSOASERVICEPROCESSINGMODELMNGD_API TCSOASERVICEPROCESSINGMODELMNGDEXPORT

/* Support TCSOASERVICEPROCESSINGMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelserviceprocessingmngd
#   if defined(__lint)
#       define TCSOASERVICEPROCESSINGMODELMNGDEXPORT       __export(tcsoamodelserviceprocessingmngd)
#       define TCSOASERVICEPROCESSINGMODELMNGDGLOBAL       extern __global(tcsoamodelserviceprocessingmngd)
#       define TCSOASERVICEPROCESSINGMODELMNGDPRIVATE      extern __private(tcsoamodelserviceprocessingmngd)
#   elif defined(_WIN32)
#       define TCSOASERVICEPROCESSINGMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOASERVICEPROCESSINGMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOASERVICEPROCESSINGMODELMNGDPRIVATE      extern
#   else
#       define TCSOASERVICEPROCESSINGMODELMNGDEXPORT
#       define TCSOASERVICEPROCESSINGMODELMNGDGLOBAL       extern
#       define TCSOASERVICEPROCESSINGMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOASERVICEPROCESSINGMODELMNGDEXPORT       __export(tcsoamodelserviceprocessingmngd)
#       define TCSOASERVICEPROCESSINGMODELMNGDGLOBAL       extern __global(tcsoamodelserviceprocessingmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOASERVICEPROCESSINGMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOASERVICEPROCESSINGMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOASERVICEPROCESSINGMODELMNGDEXPORT
#       define TCSOASERVICEPROCESSINGMODELMNGDGLOBAL       extern
#   endif
#endif

