/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelservicerequestmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOASERVICEREQUESTMODELMNGD_API, not TCSOASERVICEREQUESTMODELMNGDEXPORT */

#define TCSOASERVICEREQUESTMODELMNGD_API TCSOASERVICEREQUESTMODELMNGDEXPORT

/* Support TCSOASERVICEREQUESTMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelservicerequestmngd
#   if defined(__lint)
#       define TCSOASERVICEREQUESTMODELMNGDEXPORT       __export(tcsoamodelservicerequestmngd)
#       define TCSOASERVICEREQUESTMODELMNGDGLOBAL       extern __global(tcsoamodelservicerequestmngd)
#       define TCSOASERVICEREQUESTMODELMNGDPRIVATE      extern __private(tcsoamodelservicerequestmngd)
#   elif defined(_WIN32)
#       define TCSOASERVICEREQUESTMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOASERVICEREQUESTMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOASERVICEREQUESTMODELMNGDPRIVATE      extern
#   else
#       define TCSOASERVICEREQUESTMODELMNGDEXPORT
#       define TCSOASERVICEREQUESTMODELMNGDGLOBAL       extern
#       define TCSOASERVICEREQUESTMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOASERVICEREQUESTMODELMNGDEXPORT       __export(tcsoamodelservicerequestmngd)
#       define TCSOASERVICEREQUESTMODELMNGDGLOBAL       extern __global(tcsoamodelservicerequestmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOASERVICEREQUESTMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOASERVICEREQUESTMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOASERVICEREQUESTMODELMNGDEXPORT
#       define TCSOASERVICEREQUESTMODELMNGDGLOBAL       extern
#   endif
#endif

