/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelserviceschedulingmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOASERVICESCHEDULINGMODELMNGD_API, not TCSOASERVICESCHEDULINGMODELMNGDEXPORT */

#define TCSOASERVICESCHEDULINGMODELMNGD_API TCSOASERVICESCHEDULINGMODELMNGDEXPORT

/* Support TCSOASERVICESCHEDULINGMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelserviceschedulingmngd
#   if defined(__lint)
#       define TCSOASERVICESCHEDULINGMODELMNGDEXPORT       __export(tcsoamodelserviceschedulingmngd)
#       define TCSOASERVICESCHEDULINGMODELMNGDGLOBAL       extern __global(tcsoamodelserviceschedulingmngd)
#       define TCSOASERVICESCHEDULINGMODELMNGDPRIVATE      extern __private(tcsoamodelserviceschedulingmngd)
#   elif defined(_WIN32)
#       define TCSOASERVICESCHEDULINGMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOASERVICESCHEDULINGMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOASERVICESCHEDULINGMODELMNGDPRIVATE      extern
#   else
#       define TCSOASERVICESCHEDULINGMODELMNGDEXPORT
#       define TCSOASERVICESCHEDULINGMODELMNGDGLOBAL       extern
#       define TCSOASERVICESCHEDULINGMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOASERVICESCHEDULINGMODELMNGDEXPORT       __export(tcsoamodelserviceschedulingmngd)
#       define TCSOASERVICESCHEDULINGMODELMNGDGLOBAL       extern __global(tcsoamodelserviceschedulingmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOASERVICESCHEDULINGMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOASERVICESCHEDULINGMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOASERVICESCHEDULINGMODELMNGDEXPORT
#       define TCSOASERVICESCHEDULINGMODELMNGDGLOBAL       extern
#   endif
#endif

