/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelserviceeventmanagementmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOASERVICEEVENTMANAGEMENTMODELMNGD_API, not TCSOASERVICEEVENTMANAGEMENTMODELMNGDEXPORT */

#define TCSOASERVICEEVENTMANAGEMENTMODELMNGD_API TCSOASERVICEEVENTMANAGEMENTMODELMNGDEXPORT

/* Support TCSOASERVICEEVENTMANAGEMENTMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelserviceeventmanagementmngd
#   if defined(__lint)
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDEXPORT       __export(tcsoamodelserviceeventmanagementmngd)
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDGLOBAL       extern __global(tcsoamodelserviceeventmanagementmngd)
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDPRIVATE      extern __private(tcsoamodelserviceeventmanagementmngd)
#   elif defined(_WIN32)
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDPRIVATE      extern
#   else
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDEXPORT
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDGLOBAL       extern
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDEXPORT       __export(tcsoamodelserviceeventmanagementmngd)
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDGLOBAL       extern __global(tcsoamodelserviceeventmanagementmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDEXPORT
#       define TCSOASERVICEEVENTMANAGEMENTMODELMNGDGLOBAL       extern
#   endif
#endif

