/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelvendormanagementmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAVENDORMANAGEMENTMODELMNGD_API, not TCSOAVENDORMANAGEMENTMODELMNGDEXPORT */

#define TCSOAVENDORMANAGEMENTMODELMNGD_API TCSOAVENDORMANAGEMENTMODELMNGDEXPORT

/* Support TCSOAVENDORMANAGEMENTMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelvendormanagementmngd
#   if defined(__lint)
#       define TCSOAVENDORMANAGEMENTMODELMNGDEXPORT       __export(tcsoamodelvendormanagementmngd)
#       define TCSOAVENDORMANAGEMENTMODELMNGDGLOBAL       extern __global(tcsoamodelvendormanagementmngd)
#       define TCSOAVENDORMANAGEMENTMODELMNGDPRIVATE      extern __private(tcsoamodelvendormanagementmngd)
#   elif defined(_WIN32)
#       define TCSOAVENDORMANAGEMENTMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOAVENDORMANAGEMENTMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOAVENDORMANAGEMENTMODELMNGDPRIVATE      extern
#   else
#       define TCSOAVENDORMANAGEMENTMODELMNGDEXPORT
#       define TCSOAVENDORMANAGEMENTMODELMNGDGLOBAL       extern
#       define TCSOAVENDORMANAGEMENTMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAVENDORMANAGEMENTMODELMNGDEXPORT       __export(tcsoamodelvendormanagementmngd)
#       define TCSOAVENDORMANAGEMENTMODELMNGDGLOBAL       extern __global(tcsoamodelvendormanagementmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAVENDORMANAGEMENTMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOAVENDORMANAGEMENTMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAVENDORMANAGEMENTMODELMNGDEXPORT
#       define TCSOAVENDORMANAGEMENTMODELMNGDGLOBAL       extern
#   endif
#endif

