/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodelweldmgmtmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAWELDMGMTMODELMNGD_API, not TCSOAWELDMGMTMODELMNGDEXPORT */

#define TCSOAWELDMGMTMODELMNGD_API TCSOAWELDMGMTMODELMNGDEXPORT

/* Support TCSOAWELDMGMTMODELMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodelweldmgmtmngd
#   if defined(__lint)
#       define TCSOAWELDMGMTMODELMNGDEXPORT       __export(tcsoamodelweldmgmtmngd)
#       define TCSOAWELDMGMTMODELMNGDGLOBAL       extern __global(tcsoamodelweldmgmtmngd)
#       define TCSOAWELDMGMTMODELMNGDPRIVATE      extern __private(tcsoamodelweldmgmtmngd)
#   elif defined(_WIN32)
#       define TCSOAWELDMGMTMODELMNGDEXPORT       __declspec(dllexport)
#       define TCSOAWELDMGMTMODELMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOAWELDMGMTMODELMNGDPRIVATE      extern
#   else
#       define TCSOAWELDMGMTMODELMNGDEXPORT
#       define TCSOAWELDMGMTMODELMNGDGLOBAL       extern
#       define TCSOAWELDMGMTMODELMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAWELDMGMTMODELMNGDEXPORT       __export(tcsoamodelweldmgmtmngd)
#       define TCSOAWELDMGMTMODELMNGDGLOBAL       extern __global(tcsoamodelweldmgmtmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAWELDMGMTMODELMNGDEXPORT      __declspec(dllimport)
#       define TCSOAWELDMGMTMODELMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAWELDMGMTMODELMNGDEXPORT
#       define TCSOAWELDMGMTMODELMNGDGLOBAL       extern
#   endif
#endif

