/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libcls0soaclassificationcorestrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use CLS0SOACLASSIFICATIONCORESTRONGMNGD_API, not CLS0SOACLASSIFICATIONCORESTRONGMNGDEXPORT */

#define CLS0SOACLASSIFICATIONCORESTRONGMNGD_API CLS0SOACLASSIFICATIONCORESTRONGMNGDEXPORT

/* Support CLS0SOACLASSIFICATIONCORESTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libcls0soaclassificationcorestrongmngd
#   if defined(__lint)
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDEXPORT       __export(cls0soaclassificationcorestrongmngd)
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDGLOBAL       extern __global(cls0soaclassificationcorestrongmngd)
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDPRIVATE      extern __private(cls0soaclassificationcorestrongmngd)
#   elif defined(_WIN32)
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDEXPORT       __declspec(dllexport)
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDPRIVATE      extern
#   else
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDEXPORT
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDGLOBAL       extern
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDEXPORT       __export(cls0soaclassificationcorestrongmngd)
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDGLOBAL       extern __global(cls0soaclassificationcorestrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDEXPORT      __declspec(dllimport)
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDEXPORT
#       define CLS0SOACLASSIFICATIONCORESTRONGMNGDGLOBAL       extern
#   endif
#endif

