/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libfnd0soaconfiguratoradminstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use FND0SOACONFIGURATORADMINSTRONGMNGD_API, not FND0SOACONFIGURATORADMINSTRONGMNGDEXPORT */

#define FND0SOACONFIGURATORADMINSTRONGMNGD_API FND0SOACONFIGURATORADMINSTRONGMNGDEXPORT

/* Support FND0SOACONFIGURATORADMINSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libfnd0soaconfiguratoradminstrongmngd
#   if defined(__lint)
#       define FND0SOACONFIGURATORADMINSTRONGMNGDEXPORT       __export(fnd0soaconfiguratoradminstrongmngd)
#       define FND0SOACONFIGURATORADMINSTRONGMNGDGLOBAL       extern __global(fnd0soaconfiguratoradminstrongmngd)
#       define FND0SOACONFIGURATORADMINSTRONGMNGDPRIVATE      extern __private(fnd0soaconfiguratoradminstrongmngd)
#   elif defined(_WIN32)
#       define FND0SOACONFIGURATORADMINSTRONGMNGDEXPORT       __declspec(dllexport)
#       define FND0SOACONFIGURATORADMINSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define FND0SOACONFIGURATORADMINSTRONGMNGDPRIVATE      extern
#   else
#       define FND0SOACONFIGURATORADMINSTRONGMNGDEXPORT
#       define FND0SOACONFIGURATORADMINSTRONGMNGDGLOBAL       extern
#       define FND0SOACONFIGURATORADMINSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define FND0SOACONFIGURATORADMINSTRONGMNGDEXPORT       __export(fnd0soaconfiguratoradminstrongmngd)
#       define FND0SOACONFIGURATORADMINSTRONGMNGDGLOBAL       extern __global(fnd0soaconfiguratoradminstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define FND0SOACONFIGURATORADMINSTRONGMNGDEXPORT      __declspec(dllimport)
#       define FND0SOACONFIGURATORADMINSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define FND0SOACONFIGURATORADMINSTRONGMNGDEXPORT
#       define FND0SOACONFIGURATORADMINSTRONGMNGDGLOBAL       extern
#   endif
#endif

