// Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
// ==================================================
// Copyright 2012
// Siemens Product Lifecycle Management Software Inc.
// All Rights Reserved.
// ==================================================
// Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

#ifndef TEAMCENTER_SOA_CLIENT_RULEPATTERNIMPL_HXX
#define TEAMCENTER_SOA_CLIENT_RULEPATTERNIMPL_HXX

#include <string>
#include <new>
#include <teamcenter/soa/common/MemoryManager.hxx>

#include <teamcenter/soa/client/RulePattern.hxx>






namespace Teamcenter
{
    namespace Soa
    {
        namespace Client
        {

/**
 *  Default implementation of RulePattern
 */
class RulePatternImpl : public RulePattern
{
public:


    /**
     * Constructor
     * @param pattern
     * @param autoGen
     * @param initVal
     * @param maxVal
     *
     * @unpublished
     */
    RulePatternImpl( const std::string& pattern, bool autoGen, int initVal, int maxVal );
    ~RulePatternImpl();
    SOA_CLASS_NEW_OPERATORS

    virtual std::string getPattern() const;
    virtual bool isAutogenerated() const;
    virtual int getInitialValue() const;
    virtual int getMaximumValue() const;



private:
    RulePatternImpl(); // do not allow use of default
    const std::string mPattern;
    const bool        mAutoGen;
    const int         mInitVal;
    const int         mMaxVal;



};

}}}//end namespace


#endif