/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoacadstrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOACADSTRONGMNGD_API, not TCSOACADSTRONGMNGDEXPORT */

#define TCSOACADSTRONGMNGD_API TCSOACADSTRONGMNGDEXPORT

/* Support TCSOACADSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoacadstrongmngd
#   if defined(__lint)
#       define TCSOACADSTRONGMNGDEXPORT       __export(tcsoacadstrongmngd)
#       define TCSOACADSTRONGMNGDGLOBAL       extern __global(tcsoacadstrongmngd)
#       define TCSOACADSTRONGMNGDPRIVATE      extern __private(tcsoacadstrongmngd)
#   elif defined(_WIN32)
#       define TCSOACADSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOACADSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOACADSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOACADSTRONGMNGDEXPORT
#       define TCSOACADSTRONGMNGDGLOBAL       extern
#       define TCSOACADSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOACADSTRONGMNGDEXPORT       __export(tcsoacadstrongmngd)
#       define TCSOACADSTRONGMNGDGLOBAL       extern __global(tcsoacadstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOACADSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOACADSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOACADSTRONGMNGDEXPORT
#       define TCSOACADSTRONGMNGDGLOBAL       extern
#   endif
#endif

