/* 
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 Copyright 2012 Siemens Product Lifecycle Management Software Inc. All Rights Reserved.

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoaquerystrongmngd

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAQUERYSTRONGMNGD_API, not TCSOAQUERYSTRONGMNGDEXPORT */

#define TCSOAQUERYSTRONGMNGD_API TCSOAQUERYSTRONGMNGDEXPORT

/* Support TCSOAQUERYSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoaquerystrongmngd
#   if defined(__lint)
#       define TCSOAQUERYSTRONGMNGDEXPORT       __export(tcsoaquerystrongmngd)
#       define TCSOAQUERYSTRONGMNGDGLOBAL       extern __global(tcsoaquerystrongmngd)
#       define TCSOAQUERYSTRONGMNGDPRIVATE      extern __private(tcsoaquerystrongmngd)
#   elif defined(_WIN32)
#       define TCSOAQUERYSTRONGMNGDEXPORT       __declspec(dllexport)
#       define TCSOAQUERYSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define TCSOAQUERYSTRONGMNGDPRIVATE      extern
#   else
#       define TCSOAQUERYSTRONGMNGDEXPORT
#       define TCSOAQUERYSTRONGMNGDGLOBAL       extern
#       define TCSOAQUERYSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAQUERYSTRONGMNGDEXPORT       __export(tcsoaquerystrongmngd)
#       define TCSOAQUERYSTRONGMNGDGLOBAL       extern __global(tcsoaquerystrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAQUERYSTRONGMNGDEXPORT      __declspec(dllimport)
#       define TCSOAQUERYSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAQUERYSTRONGMNGDEXPORT
#       define TCSOAQUERYSTRONGMNGDGLOBAL       extern
#   endif
#endif

